import type { SentenceLesson } from './courseContent';

/** Second original content pack: 32 more 504 words in practical sentences. */
export const ADVANCED_SENTENCE_LESSONS: SentenceLesson[] = [
  {
    id: 'communication-solving-a-technical-problem',
    levelId: 3,
    order: 16,
    title: 'حل یک مشکل فنی',
    subtitle: 'بررسی دقیق مشکل و پیشنهاد راه‌حل',
    situation: 'یک وسیله درست کار نمی‌کند و باید مشکل را با همکارتان بررسی و یک راه‌حل عملی پیدا کنید.',
    durationMinutes: 13,
    sentences: [
      { id: 'technical-defect', en: 'We found a defect in the new device.', fa: 'یک نقص در دستگاه جدید پیدا کردیم.', pronunciation: 'وی فَوند اَ دیفِکت این ذِ نیو دِوایس', vocabulary: [{ word: 'defect', meaning: 'نقص / ایراد', essential504: true }] },
      { id: 'technical-eliminate', en: 'First, we need to eliminate the simple causes.', fa: 'ابتدا باید علت‌های ساده را حذف کنیم.', pronunciation: 'فِرست، وی نید تو اِلیمِنِیت ذِ سیمپِل کازِز', vocabulary: [{ word: 'eliminate', meaning: 'حذف کردن', essential504: true }] },
      { id: 'technical-utilize', en: 'We can utilize the backup system for now.', fa: 'فعلاً می‌توانیم از سیستم پشتیبان استفاده کنیم.', pronunciation: 'وی کَن یوتِلایز ذِ بَک‌آپ سیستم فُر ناو', vocabulary: [{ word: 'utilize', meaning: 'به‌کار گرفتن / استفاده کردن', essential504: true }] },
      { id: 'technical-comprehensive', en: 'The team will prepare a comprehensive report.', fa: 'تیم یک گزارش جامع آماده می‌کند.', pronunciation: 'ذِ تیم ویل پریپِر اَ کامپریهِنسِو ریپورت', vocabulary: [{ word: 'comprehensive', meaning: 'جامع و کامل', essential504: true }] },
      { id: 'technical-restart', en: 'Please restart the device once.', fa: 'لطفاً دستگاه را یک بار راه‌اندازی مجدد کنید.', pronunciation: 'پلیز ری‌اِستارت ذِ دِوایس وانس', vocabulary: [{ word: 'restart', meaning: 'راه‌اندازی مجدد' }] },
      { id: 'technical-update', en: 'I will update you when we know more.', fa: 'وقتی اطلاعات بیشتری داشتیم شما را مطلع می‌کنم.', pronunciation: 'آی ویل آپدِیت یو وِن وی نو مور', vocabulary: [{ word: 'update', meaning: 'مطلع‌کردن / به‌روزرسانی' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What is wrong with the device?', fa: 'مشکل دستگاه چیست؟' },
      { speaker: 'learner', text: 'We found a defect, but we can utilize the backup system.', fa: 'یک نقص پیدا کردیم، اما می‌توانیم از سیستم پشتیبان استفاده کنیم.' },
      { speaker: 'partner', text: 'What happens next?', fa: 'بعد چه می‌شود؟' },
      { speaker: 'learner', text: 'We will eliminate the possible causes and prepare a comprehensive report.', fa: 'علت‌های احتمالی را حذف می‌کنیم و گزارشی جامع آماده می‌کنیم.' },
    ],
  },
  {
    id: 'communication-mountain-trip',
    levelId: 3,
    order: 17,
    title: 'توصیف یک سفر کوهستانی',
    subtitle: 'تعریف اتفاقات و تغییرات طبیعت',
    situation: 'برای دوستتان تعریف می‌کنید که در یک سفر کوهستانی چه دیدید و شرایط چگونه تغییر کرد.',
    durationMinutes: 12,
    sentences: [
      { id: 'mountain-descend', en: 'We began to descend before sunset.', fa: 'پیش از غروب شروع به پایین‌آمدن کردیم.', pronunciation: 'وی بِگَن تو دیسِند بیفور سان‌سِت', vocabulary: [{ word: 'descend', meaning: 'پایین آمدن', essential504: true }] },
      { id: 'mountain-enormous', en: 'An enormous mountain stood ahead of us.', fa: 'کوهی عظیم روبه‌روی ما قرار داشت.', pronunciation: 'اَن اِنورمِس ماونتِن اِستود اَهِد آو آس', vocabulary: [{ word: 'enormous', meaning: 'بسیار بزرگ / عظیم', essential504: true }] },
      { id: 'mountain-vapor', en: 'Water vapor rose from the warm ground.', fa: 'بخار آب از زمین گرم بالا آمد.', pronunciation: 'واتِر وِیپِر روز فرام ذِ وُرم گِرَوند', vocabulary: [{ word: 'vapor', meaning: 'بخار', essential504: true }] },
      { id: 'mountain-vanish', en: 'The path seemed to vanish in the fog.', fa: 'به نظر می‌رسید مسیر در مه ناپدید شده است.', pronunciation: 'ذِ پَث سیمد تو وَنیش این ذِ فاگ', vocabulary: [{ word: 'vanish', meaning: 'ناپدید شدن', essential504: true }] },
      { id: 'mountain-map', en: 'We checked the map carefully.', fa: 'نقشه را با دقت بررسی کردیم.', pronunciation: 'وی چِکت ذِ مَپ کِرفولی', vocabulary: [{ word: 'carefully', meaning: 'با دقت' }] },
      { id: 'mountain-return', en: 'We returned safely before dark.', fa: 'پیش از تاریکی به‌سلامت برگشتیم.', pronunciation: 'وی ریتِرند سِیفلی بیفور دارک', vocabulary: [{ word: 'safely', meaning: 'به‌سلامت' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why did you descend early?', fa: 'چرا زود پایین آمدید؟' },
      { speaker: 'learner', text: 'The path began to vanish in the fog.', fa: 'مسیر در مه شروع به ناپدیدشدن کرد.' },
      { speaker: 'partner', text: 'Was the mountain large?', fa: 'کوه بزرگ بود؟' },
      { speaker: 'learner', text: 'Yes, it was enormous.', fa: 'بله، بسیار عظیم بود.' },
    ],
  },
  {
    id: 'communication-public-discussion',
    levelId: 3,
    order: 18,
    title: 'بحث درباره یک مسئله عمومی',
    subtitle: 'پرسیدن سؤال‌های دقیق و ماندن روی موضوع',
    situation: 'در یک جلسه عمومی شرکت کرده‌اید و می‌خواهید مسئول جلسه پاسخ روشن و مرتبطی بدهد.',
    durationMinutes: 13,
    sentences: [
      { id: 'public-topic', en: 'Let us stay focused on the main topic.', fa: 'بیایید روی موضوع اصلی متمرکز بمانیم.', pronunciation: 'لِت آس اِستِی فوکِست آن ذِ مِین تاپیک', vocabulary: [{ word: 'topic', meaning: 'موضوع', essential504: true }] },
      { id: 'public-burden', en: 'The new cost will be a burden on families.', fa: 'هزینه جدید باری بر دوش خانواده‌ها خواهد بود.', pronunciation: 'ذِ نیو کاست ویل بی اَ بِردِن آن فَمِلیز', vocabulary: [{ word: 'burden', meaning: 'بار / مسئولیت سنگین', essential504: true }] },
      { id: 'public-evade', en: 'Please do not evade the question.', fa: 'لطفاً از پاسخ به سؤال طفره نروید.', pronunciation: 'پلیز دو نات ایوِید ذِ کوئسچِن', vocabulary: [{ word: 'evade', meaning: 'طفره رفتن / اجتناب کردن', essential504: true }] },
      { id: 'public-probe', en: 'We need to probe the cause of the problem.', fa: 'باید علت مشکل را دقیق بررسی کنیم.', pronunciation: 'وی نید تو پروب ذِ کاز آو ذِ پرابلِم', vocabulary: [{ word: 'probe', meaning: 'بررسی دقیق کردن', essential504: true }] },
      { id: 'public-evidence', en: 'What evidence supports this decision?', fa: 'چه مدرکی از این تصمیم حمایت می‌کند؟', pronunciation: 'وات اِویدِنس ساپورتس ذیس دِسیژِن؟', vocabulary: [{ word: 'evidence', meaning: 'مدرک / شواهد' }] },
      { id: 'public-answer', en: 'We need a clear and honest answer.', fa: 'به پاسخی روشن و صادقانه نیاز داریم.', pronunciation: 'وی نید اَ کلیر اَند آنِست اَنسِر', vocabulary: [{ word: 'honest', meaning: 'صادقانه' }] },
    ],
    dialogue: [
      { speaker: 'learner', text: 'The new cost will be a burden on families.', fa: 'هزینه جدید برای خانواده‌ها سنگین خواهد بود.' },
      { speaker: 'partner', text: 'We can discuss that later.', fa: 'بعداً می‌توانیم درباره آن صحبت کنیم.' },
      { speaker: 'learner', text: 'Please do not evade the question. It is the main topic.', fa: 'لطفاً از سؤال طفره نروید. این موضوع اصلی است.' },
    ],
  },
  {
    id: 'communication-avoiding-an-online-scam',
    levelId: 3,
    order: 19,
    title: 'تشخیص پیشنهاد مشکوک',
    subtitle: 'محافظت از خود در فضای آنلاین',
    situation: 'پیامی با یک پیشنهاد غیرعادی دریافت کرده‌اید و می‌خواهید پیش از پاسخ‌دادن، قابل‌اعتمادبودن آن را بررسی کنید.',
    durationMinutes: 13,
    sentences: [
      { id: 'scam-deceive', en: 'The message was designed to deceive people.', fa: 'این پیام برای فریب‌دادن مردم طراحی شده بود.', pronunciation: 'ذِ مِسِج واز دیزایند تو دیسیو پیپِل', vocabulary: [{ word: 'deceive', meaning: 'فریب دادن', essential504: true }] },
      { id: 'scam-security', en: 'Never share your security code.', fa: 'هرگز کد امنیتی خود را به اشتراک نگذارید.', pronunciation: 'نِوِر شِر یور سِکیورِتی کود', vocabulary: [{ word: 'security', meaning: 'امنیت', essential504: true }] },
      { id: 'scam-sinister', en: 'There may be a sinister purpose behind the offer.', fa: 'ممکن است هدفی شرورانه پشت این پیشنهاد باشد.', pronunciation: 'ذِر مِی بی اَ سینِستِر پِرپِس بیهایند ذی آفِر', vocabulary: [{ word: 'sinister', meaning: 'شوم / شرورانه', essential504: true }] },
      { id: 'scam-undoubtedly', en: 'This link is undoubtedly unsafe.', fa: 'این پیوند بدون شک ناامن است.', pronunciation: 'ذیس لینک ایز آنداوتِدلی اَنسِیف', vocabulary: [{ word: 'undoubtedly', meaning: 'بدون شک', essential504: true }] },
      { id: 'scam-delete', en: 'I will report and delete the message.', fa: 'پیام را گزارش و حذف می‌کنم.', pronunciation: 'آی ویل ریپورت اَند دیلیت ذِ مِسِج', vocabulary: [{ word: 'report', meaning: 'گزارش‌کردن' }] },
      { id: 'scam-verify', en: 'Always verify the sender first.', fa: 'همیشه ابتدا فرستنده را بررسی کنید.', pronunciation: 'آلوِیز وِریفای ذِ سِندِر فِرست', vocabulary: [{ word: 'verify', meaning: 'بررسی و تأیید کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Should I open this link?', fa: 'آیا باید این پیوند را باز کنم؟' },
      { speaker: 'learner', text: 'No. It is undoubtedly unsafe.', fa: 'نه. بدون شک ناامن است.' },
      { speaker: 'partner', text: 'What should I do?', fa: 'چه کار باید بکنم؟' },
      { speaker: 'learner', text: 'Do not share your security code. Report and delete the message.', fa: 'کد امنیتی را به اشتراک نگذار. پیام را گزارش و حذف کن.' },
    ],
  },
  {
    id: 'advanced-planning-an-outdoor-event',
    levelId: 4,
    order: 20,
    title: 'برنامه‌ریزی یک رویداد',
    subtitle: 'تصمیم‌گیری در شرایط نامطمئن',
    situation: 'برای یک رویداد بزرگ در فضای باز برنامه‌ریزی می‌کنید، اما پیش‌بینی هوا نگران‌کننده است.',
    durationMinutes: 14,
    sentences: [
      { id: 'event-massive', en: 'A massive crowd is expected tomorrow.', fa: 'انتظار می‌رود فردا جمعیت بسیار بزرگی حضور پیدا کند.', pronunciation: 'اَ مَسِو کِراود ایز اِکسپِکتِد تومارو', vocabulary: [{ word: 'massive', meaning: 'بسیار بزرگ / عظیم', essential504: true }] },
      { id: 'event-unique', en: 'This event offers a unique experience.', fa: 'این رویداد تجربه‌ای منحصربه‌فرد ارائه می‌دهد.', pronunciation: 'ذیس ایوِنت آفِرز اَ یونیک اِکسپیریِنس', vocabulary: [{ word: 'unique', meaning: 'منحصربه‌فرد', essential504: true }] },
      { id: 'event-torrent', en: 'A torrent of rain could flood the field.', fa: 'باران سیل‌آسا ممکن است زمین را آب بگیرد.', pronunciation: 'اَ تورِنت آو رِین کود فِلاد ذِ فیلد', vocabulary: [{ word: 'torrent', meaning: 'جریان شدید / سیل‌آسا', essential504: true }] },
      { id: 'event-gloomy', en: 'The weather forecast looks gloomy.', fa: 'پیش‌بینی هوا ناامیدکننده به نظر می‌رسد.', pronunciation: 'ذِ وِذِر فورکَست لوکس گِلومی', vocabulary: [{ word: 'gloomy', meaning: 'دلگیر / ناامیدکننده', essential504: true }] },
      { id: 'event-indoor', en: 'We should prepare an indoor location.', fa: 'باید یک مکان سرپوشیده آماده کنیم.', pronunciation: 'وی شود پریپِر اَن ایندور لوکِیشِن', vocabulary: [{ word: 'indoor', meaning: 'سرپوشیده' }] },
      { id: 'event-notify', en: 'We will notify everyone tonight.', fa: 'امشب همه را مطلع خواهیم کرد.', pronunciation: 'وی ویل نوتیفای اِوری‌وان تِنایت', vocabulary: [{ word: 'notify', meaning: 'مطلع کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'The forecast looks gloomy. Should we cancel?', fa: 'پیش‌بینی هوا خوب نیست. باید لغو کنیم؟' },
      { speaker: 'learner', text: 'Not yet. We expect a massive crowd, so let us prepare an indoor location.', fa: 'هنوز نه. انتظار جمعیت زیادی داریم، پس یک مکان سرپوشیده آماده کنیم.' },
      { speaker: 'partner', text: 'Good. We will notify everyone tonight.', fa: 'خوب است. امشب همه را مطلع می‌کنیم.' },
    ],
  },
  {
    id: 'advanced-developing-a-skill',
    levelId: 4,
    order: 21,
    title: 'پیشرفت در یک مهارت',
    subtitle: 'صحبت واقع‌بینانه درباره توانایی',
    situation: 'با مربی خود درباره سطح فعلی، نقاط قوت و راه پیشرفت در یک مهارت تازه صحبت می‌کنید.',
    durationMinutes: 14,
    sentences: [
      { id: 'skill-amateur', en: 'I am still an amateur photographer.', fa: 'من هنوز یک عکاس آماتور هستم.', pronunciation: 'آی اَم اِستیل اَن اَمِچور فِتاگِرَفِر', vocabulary: [{ word: 'amateur', meaning: 'تازه‌کار / غیرحرفه‌ای', essential504: true }] },
      { id: 'skill-mediocre', en: 'My early work was mediocre.', fa: 'کارهای اولیه من معمولی و متوسط بودند.', pronunciation: 'مای اِرلی وِرک واز میدیوکِر', vocabulary: [{ word: 'mediocre', meaning: 'متوسط / نه‌چندان خوب', essential504: true }] },
      { id: 'skill-variety', en: 'Practice a variety of techniques.', fa: 'روش‌های گوناگونی را تمرین کنید.', pronunciation: 'پِرَکتیس اَ وِرایِتی آو تِکنیکس', vocabulary: [{ word: 'variety', meaning: 'تنوع / گوناگونی', essential504: true }] },
      { id: 'skill-prominent', en: 'She became a prominent artist through practice.', fa: 'او با تمرین به هنرمندی برجسته تبدیل شد.', pronunciation: 'شی بِکِیم اَ پرامِنِنت آرتیست ثرو پِرَکتیس', vocabulary: [{ word: 'prominent', meaning: 'برجسته / شناخته‌شده', essential504: true }] },
      { id: 'skill-feedback', en: 'Honest feedback helps me improve.', fa: 'بازخورد صادقانه به پیشرفت من کمک می‌کند.', pronunciation: 'آنِست فیدبَک هِلپس می ایمپروو', vocabulary: [{ word: 'feedback', meaning: 'بازخورد' }] },
      { id: 'skill-patient', en: 'I need to be patient with myself.', fa: 'باید با خودم صبور باشم.', pronunciation: 'آی نید تو بی پِیشِنت ویذ مایسِلف', vocabulary: [{ word: 'patient', meaning: 'صبور' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'How would you describe your level?', fa: 'سطحتان را چگونه توصیف می‌کنید؟' },
      { speaker: 'learner', text: 'I am still an amateur, and some of my work is mediocre.', fa: 'هنوز تازه‌کارم و بعضی کارهایم متوسط هستند.' },
      { speaker: 'partner', text: 'Practice a variety of techniques and ask for feedback.', fa: 'روش‌های مختلف را تمرین کنید و بازخورد بگیرید.' },
    ],
  },
  {
    id: 'advanced-discussing-a-rumor',
    levelId: 4,
    order: 22,
    title: 'بررسی یک شایعه',
    subtitle: 'جلوگیری از انتشار اطلاعات نادرست',
    situation: 'یک داستان عجیب در فضای مجازی پخش شده است و با دوستتان درباره اعتبار آن صحبت می‌کنید.',
    durationMinutes: 13,
    sentences: [
      { id: 'rumor-circulate', en: 'False stories circulate quickly online.', fa: 'داستان‌های نادرست به‌سرعت در اینترنت پخش می‌شوند.', pronunciation: 'فالس اِستوریز سِرکیولِیت کوییکلی آنلاین', vocabulary: [{ word: 'circulate', meaning: 'پخش و منتشر شدن', essential504: true }] },
      { id: 'rumor-exaggerate', en: 'Some people exaggerate the details.', fa: 'بعضی افراد در جزئیات اغراق می‌کنند.', pronunciation: 'سام پیپِل اِگْزَجِرِیت ذِ دیتِیلز', vocabulary: [{ word: 'exaggerate', meaning: 'اغراق کردن', essential504: true }] },
      { id: 'rumor-villain', en: 'The story unfairly made him look like a villain.', fa: 'داستان به‌ناحق او را مانند یک فرد شرور نشان داد.', pronunciation: 'ذِ اِستوری آنفِرلی مِید هیم لوک لایک اَ ویلِن', vocabulary: [{ word: 'villain', meaning: 'فرد شرور', essential504: true }] },
      { id: 'rumor-weird', en: 'The claim sounds weird, but that does not make it true.', fa: 'این ادعا عجیب به نظر می‌رسد، اما این به معنای درست‌بودنش نیست.', pronunciation: 'ذِ کِلِیم ساوندز ویرد، بات ذَت داز نات مِیک ایت ترو', vocabulary: [{ word: 'weird', meaning: 'عجیب', essential504: true }] },
      { id: 'rumor-source', en: 'Check the original source before sharing.', fa: 'پیش از اشتراک‌گذاری، منبع اصلی را بررسی کنید.', pronunciation: 'چِک ذی اریجِنِل سورس بیفور شِرینگ', vocabulary: [{ word: 'source', meaning: 'منبع' }] },
      { id: 'rumor-correct', en: 'We should correct false information.', fa: 'باید اطلاعات نادرست را اصلاح کنیم.', pronunciation: 'وی شود کِرِکت فالس اینفِرمِیشِن', vocabulary: [{ word: 'correct', meaning: 'اصلاح کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'This story sounds weird. Should I share it?', fa: 'این داستان عجیب است. آن را منتشر کنم؟' },
      { speaker: 'learner', text: 'No. People often exaggerate details, and false stories circulate quickly.', fa: 'نه. مردم اغلب اغراق می‌کنند و داستان‌های نادرست سریع پخش می‌شوند.' },
      { speaker: 'partner', text: 'I will check the original source first.', fa: 'ابتدا منبع اصلی را بررسی می‌کنم.' },
    ],
  },
  {
    id: 'advanced-friendly-game-night',
    levelId: 4,
    order: 23,
    title: 'یک شب بازی دوستانه',
    subtitle: 'پیشنهاد، شرط دوستانه و استراحت',
    situation: 'پس از یک روز طولانی با دوستانتان استراحت می‌کنید و درباره شرکت در یک بازی دوستانه تصمیم می‌گیرید.',
    durationMinutes: 12,
    sentences: [
      { id: 'game-recline', en: 'You can recline in this chair and relax.', fa: 'می‌توانی روی این صندلی تکیه بدهی و استراحت کنی.', pronunciation: 'یو کَن ریکِلاین این ذیس چِر اَند ریلَکس', vocabulary: [{ word: 'recline', meaning: 'تکیه‌دادن / لم‌دادن', essential504: true }] },
      { id: 'game-tempt', en: 'Do not tempt me with another game.', fa: 'من را برای یک بازی دیگر وسوسه نکن.', pronunciation: 'دو نات تِمپت می ویذ اَناذِر گِیم', vocabulary: [{ word: 'tempt', meaning: 'وسوسه کردن', essential504: true }] },
      { id: 'game-wager', en: 'Let us make a small friendly wager.', fa: 'بیایید یک شرط کوچک دوستانه ببندیم.', pronunciation: 'لِت آس مِیک اَ اِسمال فِرِندلی وِیجِر', vocabulary: [{ word: 'wager', meaning: 'شرط / شرط‌بندی کردن', essential504: true }] },
      { id: 'game-popular', en: 'This game is popular with our friends.', fa: 'این بازی میان دوستانمان محبوب است.', pronunciation: 'ذیس گِیم ایز پاپیولِر ویذ آور فِرِندز', vocabulary: [{ word: 'popular', meaning: 'محبوب', essential504: true }] },
      { id: 'game-rules', en: 'Please explain the rules first.', fa: 'لطفاً ابتدا قوانین را توضیح بده.', pronunciation: 'پلیز اِکسپِلِین ذِ رولز فِرست', vocabulary: [{ word: 'rules', meaning: 'قوانین' }] },
      { id: 'game-fun', en: 'Remember, we are playing for fun.', fa: 'یادتان باشد، برای سرگرمی بازی می‌کنیم.', pronunciation: 'ریمِمبِر، وی آر پِلِیینگ فُر فان', vocabulary: [{ word: 'for fun', meaning: 'برای سرگرمی' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'This game is popular. Do you want to play?', fa: 'این بازی محبوب است. می‌خواهی بازی کنی؟' },
      { speaker: 'learner', text: 'Do not tempt me. I planned to recline and relax.', fa: 'وسوسه‌ام نکن. قصد داشتم استراحت کنم.' },
      { speaker: 'partner', text: 'How about a small friendly wager?', fa: 'یک شرط کوچک دوستانه چطور است؟' },
      { speaker: 'learner', text: 'All right, but we are playing for fun.', fa: 'باشد، اما برای سرگرمی بازی می‌کنیم.' },
    ],
  },
];
