import type { SentenceLesson } from './courseContent';

/** Fourth original content pack: 32 more 504 words in practical contexts. */
export const ADVANCED_SENTENCE_LESSONS_3: SentenceLesson[] = [
  {
    id: 'advanced-reaching-a-team-decision', levelId: 4, order: 32,
    title: 'رسیدن به تصمیم گروهی', subtitle: 'بازبینی برنامه و گرفتن تعهد',
    situation: 'اعضای تیم باید برنامه‌ای را اصلاح کنند و پیش از شروع کار روی تصمیم نهایی به توافق برسند.', durationMinutes: 14,
    sentences: [
      { id: 'team-revise', en: 'We need to revise the original plan.', fa: 'باید برنامه اولیه را بازبینی کنیم.', pronunciation: 'وی نید تو ریوایز ذی اریجِنِل پِلَن', vocabulary: [{ word: 'revise', meaning: 'بازبینی و اصلاح کردن', essential504: true }] },
      { id: 'team-pledge', en: 'Each member must pledge to finish their part.', fa: 'هر عضو باید متعهد شود بخش خود را تمام کند.', pronunciation: 'ایچ مِمبِر ماست پِلِج تو فینیش ذِر پارت', vocabulary: [{ word: 'pledge', meaning: 'تعهد دادن', essential504: true }] },
      { id: 'team-unanimous', en: 'The final decision was unanimous.', fa: 'تصمیم نهایی با موافقت همه گرفته شد.', pronunciation: 'ذِ فاینِل دِسیژِن واز یونَنِمِس', vocabulary: [{ word: 'unanimous', meaning: 'با موافقت همه / یک‌صدا', essential504: true }] },
      { id: 'team-pioneer', en: 'Our team hopes to pioneer a better method.', fa: 'تیم ما امیدوار است روش بهتری را برای نخستین‌بار ایجاد کند.', pronunciation: 'آور تیم هوپس تو پایِنیر اَ بِتِر مِثِد', vocabulary: [{ word: 'pioneer', meaning: 'پیشگام‌شدن / راه تازه بازکردن', essential504: true }] },
      { id: 'team-deadline', en: 'The deadline remains the same.', fa: 'مهلت نهایی بدون تغییر می‌ماند.', pronunciation: 'ذِ دِدلاین ریمِینز ذِ سِیم', vocabulary: [{ word: 'deadline', meaning: 'مهلت نهایی' }] },
      { id: 'team-summary', en: 'I will send a summary after the meeting.', fa: 'بعد از جلسه یک خلاصه می‌فرستم.', pronunciation: 'آی ویل سِند اَ سامِری اَفتِر ذِ میتینگ', vocabulary: [{ word: 'summary', meaning: 'خلاصه' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Do we need to revise the plan?', fa: 'لازم است برنامه را بازبینی کنیم؟' },
      { speaker: 'learner', text: 'Yes. Then every member should pledge to complete their part.', fa: 'بله. سپس هر عضو باید برای تکمیل بخش خود تعهد بدهد.' },
      { speaker: 'partner', text: 'Good. The final decision is unanimous.', fa: 'خوب است. همه با تصمیم نهایی موافق‌اند.' },
    ],
  },
  {
    id: 'advanced-developing-personal-potential', levelId: 4, order: 33,
    title: 'پرورش توانایی شخصی', subtitle: 'شناخت ظرفیت و ساختن اعتمادبه‌نفس',
    situation: 'با مربی خود درباره رشد شخصی، توانایی‌های فعلی و هدفی که می‌خواهید به آن برسید صحبت می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'growth-mature', en: 'Good judgment develops as we mature.', fa: 'با پخته‌ترشدن، قدرت تصمیم‌گیری خوب رشد می‌کند.', pronunciation: 'گود جاجمِنت دِوِلِپس اَز وی مَچور', vocabulary: [{ word: 'mature', meaning: 'پخته و بالغ شدن', essential504: true }] },
      { id: 'growth-surpass', en: 'You can surpass your previous results.', fa: 'می‌توانید از نتایج قبلی خود فراتر بروید.', pronunciation: 'یو کَن سِرپَس یور پریویِس ریزالتس', vocabulary: [{ word: 'surpass', meaning: 'فراتر رفتن', essential504: true }] },
      { id: 'growth-capacity', en: 'You have the capacity to learn quickly.', fa: 'شما ظرفیت یادگیری سریع را دارید.', pronunciation: 'یو هَو ذِ کَپَسِتی تو لِرن کوییکلی', vocabulary: [{ word: 'capacity', meaning: 'ظرفیت / توانایی', essential504: true }] },
      { id: 'growth-confident', en: 'Regular practice will make you more confident.', fa: 'تمرین منظم شما را مطمئن‌تر می‌کند.', pronunciation: 'رِگیولِر پِرَکتیس ویل مِیک یو مور کانفیدِنت', vocabulary: [{ word: 'confident', meaning: 'بااعتمادبه‌نفس / مطمئن', essential504: true }] },
      { id: 'growth-small', en: 'Start with one small daily action.', fa: 'با یک اقدام کوچک روزانه شروع کنید.', pronunciation: 'اِستارت ویذ وان اِسمال دِیلی اَکشِن', vocabulary: [{ word: 'daily', meaning: 'روزانه' }] },
      { id: 'growth-compare', en: 'Compare yourself only with your past self.', fa: 'خودتان را فقط با گذشته خود مقایسه کنید.', pronunciation: 'کِمپِر یورسِلف اونلی ویذ یور پَست سِلف', vocabulary: [{ word: 'compare', meaning: 'مقایسه کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Do you think I can improve?', fa: 'فکر می‌کنید بتوانم پیشرفت کنم؟' },
      { speaker: 'learner', text: 'You have the capacity to improve and surpass your previous results.', fa: 'ظرفیت پیشرفت و عبور از نتایج قبلی را دارید.' },
      { speaker: 'partner', text: 'How can I become more confident?', fa: 'چطور مطمئن‌تر شوم؟' },
      { speaker: 'learner', text: 'Practice one small action every day.', fa: 'هر روز یک اقدام کوچک را تمرین کنید.' },
    ],
  },
  {
    id: 'advanced-measuring-in-a-lab', levelId: 4, order: 34,
    title: 'اندازه‌گیری در آزمایشگاه', subtitle: 'ثبت نتیجه دقیق و کار محتاطانه',
    situation: 'در یک آزمایشگاه باید نمونه‌ای باریک را اندازه بگیرید و بدون عجله نتیجه را ثبت کنید.', durationMinutes: 14,
    sentences: [
      { id: 'lab-slender', en: 'Place the slender tube on the clean surface.', fa: 'لوله باریک را روی سطح تمیز قرار دهید.', pronunciation: 'پِلِیس ذِ اِسلِندِر تیوب آن ذِ کلین سِرفِس', vocabulary: [{ word: 'slender', meaning: 'باریک', essential504: true }] },
      { id: 'lab-accurate', en: 'We need an accurate measurement.', fa: 'به یک اندازه‌گیری دقیق نیاز داریم.', pronunciation: 'وی نید اَن اَکیورِت مِژِرمِنت', vocabulary: [{ word: 'accurate', meaning: 'دقیق', essential504: true }] },
      { id: 'lab-cautious', en: 'Be cautious when handling the glass.', fa: 'هنگام کار با شیشه محتاط باشید.', pronunciation: 'بی کاشِس وِن هَندلینگ ذِ گِلَس', vocabulary: [{ word: 'cautious', meaning: 'محتاط', essential504: true }] },
      { id: 'lab-doubt', en: 'If you doubt the result, repeat the test.', fa: 'اگر به نتیجه شک دارید، آزمایش را تکرار کنید.', pronunciation: 'ایف یو داوت ذِ ریزالت، ریپیت ذِ تِست', vocabulary: [{ word: 'doubt', meaning: 'شک داشتن', essential504: true }] },
      { id: 'lab-record', en: 'Record each number immediately.', fa: 'هر عدد را بلافاصله ثبت کنید.', pronunciation: 'ریکورد ایچ نامبِر ایمیدیِتلی', vocabulary: [{ word: 'immediately', meaning: 'بلافاصله' }] },
      { id: 'lab-check', en: 'Check the equipment before you begin.', fa: 'پیش از شروع تجهیزات را بررسی کنید.', pronunciation: 'چِک ذی اِکویپمِنت بیفور یو بِگین', vocabulary: [{ word: 'equipment', meaning: 'تجهیزات' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Is this measurement accurate?', fa: 'این اندازه‌گیری دقیق است؟' },
      { speaker: 'learner', text: 'I doubt the result, so I will repeat the test.', fa: 'به نتیجه شک دارم، پس آزمایش را تکرار می‌کنم.' },
      { speaker: 'partner', text: 'Good. Be cautious with the slender glass tube.', fa: 'خوب است. با لوله شیشه‌ای باریک محتاط باشید.' },
    ],
  },
  {
    id: 'advanced-evaluating-an-advertisement', levelId: 4, order: 35,
    title: 'بررسی یک تبلیغ', subtitle: 'تصمیم‌گیری آگاهانه پیش از خرید',
    situation: 'یک تبلیغ جذاب آنلاین دیده‌اید و پیش از خرید، ادعاها و خطرهای احتمالی آن را بررسی می‌کنید.', durationMinutes: 13,
    sentences: [
      { id: 'ad-appeal', en: 'The low price will appeal to many buyers.', fa: 'قیمت پایین برای بسیاری از خریداران جذاب خواهد بود.', pronunciation: 'ذِ لو پرایس ویل اَپیل تو مِنی بایِرز', vocabulary: [{ word: 'appeal', meaning: 'جذاب‌بودن / جذب کردن', essential504: true }] },
      { id: 'ad-wary', en: 'Be wary of promises that sound too perfect.', fa: 'نسبت به وعده‌هایی که بیش از حد عالی هستند محتاط باشید.', pronunciation: 'بی وِری آو پرامِسِز ذَت ساوند تو پِرفِکت', vocabulary: [{ word: 'wary', meaning: 'محتاط و مراقب', essential504: true }] },
      { id: 'ad-aware', en: 'Make sure you are aware of the extra fees.', fa: 'مطمئن شوید از هزینه‌های اضافی آگاه هستید.', pronunciation: 'مِیک شور یو آر اَوِر آو ذی اِکسترا فیز', vocabulary: [{ word: 'aware', meaning: 'آگاه', essential504: true }] },
      { id: 'ad-avoid', en: 'Avoid buying before you read the reviews.', fa: 'پیش از خواندن نظرها از خرید خودداری کنید.', pronunciation: 'اَوُید بایینگ بیفور یو رید ذِ ریویوز', vocabulary: [{ word: 'avoid', meaning: 'اجتناب کردن', essential504: true }] },
      { id: 'ad-return', en: 'Check the return policy carefully.', fa: 'قانون بازگرداندن کالا را با دقت بررسی کنید.', pronunciation: 'چِک ذِ ریتِرن پالِسی کِرفولی', vocabulary: [{ word: 'return policy', meaning: 'قانون بازگرداندن کالا' }] },
      { id: 'ad-compare', en: 'Compare the offer with other stores.', fa: 'پیشنهاد را با فروشگاه‌های دیگر مقایسه کنید.', pronunciation: 'کِمپِر ذی آفِر ویذ آذِر اِستورز', vocabulary: [{ word: 'offer', meaning: 'پیشنهاد' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'This price really appeals to me.', fa: 'این قیمت واقعاً برایم جذاب است.' },
      { speaker: 'learner', text: 'Be wary. Make sure you are aware of the extra fees.', fa: 'مراقب باش. مطمئن شو از هزینه‌های اضافی آگاهی.' },
      { speaker: 'partner', text: 'I will read the reviews before buying.', fa: 'پیش از خرید نظرها را می‌خوانم.' },
    ],
  },
  {
    id: 'advanced-choosing-a-healthy-meal', levelId: 4, order: 36,
    title: 'انتخاب غذای سالم', subtitle: 'بررسی مقدار و ارزش غذایی',
    situation: 'می‌خواهید برای یک روز شلوغ غذایی انتخاب کنید که هم مناسب باشد و هم انرژی کافی فراهم کند.', durationMinutes: 13,
    sentences: [
      { id: 'meal-nourish', en: 'Fresh food will nourish your body.', fa: 'غذای تازه بدن شما را تغذیه می‌کند.', pronunciation: 'فِرِش فود ویل نِریش یور بادی', vocabulary: [{ word: 'nourish', meaning: 'تغذیه کردن', essential504: true }] },
      { id: 'meal-quantity', en: 'A small quantity of salt is enough.', fa: 'مقدار کمی نمک کافی است.', pronunciation: 'اَ اِسمال کوانتِتی آو سالت ایز ایناف', vocabulary: [{ word: 'quantity', meaning: 'مقدار', essential504: true }] },
      { id: 'meal-opt', en: 'I usually opt for water instead of soda.', fa: 'معمولاً به‌جای نوشابه آب را انتخاب می‌کنم.', pronunciation: 'آی یوجوئِلی آپت فُر واتِر اینستِد آو سودا', vocabulary: [{ word: 'opt', meaning: 'انتخاب کردن', essential504: true }] },
      { id: 'meal-appropriate', en: 'This meal is appropriate for a busy day.', fa: 'این غذا برای یک روز شلوغ مناسب است.', pronunciation: 'ذیس میل ایز اَپروپریِت فُر اَ بیزی دِی', vocabulary: [{ word: 'appropriate', meaning: 'مناسب', essential504: true }] },
      { id: 'meal-label', en: 'Read the nutrition label first.', fa: 'ابتدا برچسب ارزش غذایی را بخوانید.', pronunciation: 'رید ذِ نوتریشن لِیبِل فِرست', vocabulary: [{ word: 'nutrition label', meaning: 'برچسب ارزش غذایی' }] },
      { id: 'meal-balance', en: 'Try to keep your meals balanced.', fa: 'سعی کنید غذاهایتان متعادل باشند.', pronunciation: 'تِرای تو کیپ یور میلز بَلِنست', vocabulary: [{ word: 'balanced', meaning: 'متعادل' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What should I drink with this meal?', fa: 'با این غذا چه چیزی بنوشم؟' },
      { speaker: 'learner', text: 'I would opt for water instead of soda.', fa: 'من به‌جای نوشابه آب را انتخاب می‌کنم.' },
      { speaker: 'partner', text: 'How much salt should I add?', fa: 'چقدر نمک اضافه کنم؟' },
      { speaker: 'learner', text: 'A small quantity is enough.', fa: 'مقدار کمی کافی است.' },
    ],
  },
  {
    id: 'advanced-discussing-road-safety', levelId: 4, order: 37,
    title: 'گفت‌وگو درباره ایمنی جاده', subtitle: 'شناخت رفتار خطرناک و راه اقتصادی',
    situation: 'در یک جلسه محلی درباره ایمنی عابران و راه‌های بهتر حمل‌ونقل گفت‌وگو می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'road-pedestrian', en: 'Every pedestrian needs a safe place to cross.', fa: 'هر عابر پیاده به مکانی امن برای عبور نیاز دارد.', pronunciation: 'اِوری پِدِسترین نیدز اَ سِیف پِلِیس تو کراس', vocabulary: [{ word: 'pedestrian', meaning: 'عابر پیاده', essential504: true }] },
      { id: 'road-reckless', en: 'Reckless driving puts everyone at risk.', fa: 'رانندگی بی‌پروا همه را در معرض خطر قرار می‌دهد.', pronunciation: 'رِکلِس دِرایوینگ پوتس اِوری‌وان اَت ریسک', vocabulary: [{ word: 'reckless', meaning: 'بی‌پروا / بی‌احتیاط', essential504: true }] },
      { id: 'road-harsh', en: 'Harsh weather makes the road more dangerous.', fa: 'هوای سخت و نامساعد جاده را خطرناک‌تر می‌کند.', pronunciation: 'هارش وِذِر مِیکس ذِ رود مور دِینجِرِس', vocabulary: [{ word: 'harsh', meaning: 'سخت / نامساعد', essential504: true }] },
      { id: 'road-economical', en: 'Public transport is often more economical.', fa: 'حمل‌ونقل عمومی اغلب اقتصادی‌تر است.', pronunciation: 'پابلیک تِرَنسپورت ایز آفِن مور اِکِنامیکِل', vocabulary: [{ word: 'economical', meaning: 'اقتصادی و کم‌هزینه', essential504: true }] },
      { id: 'road-light', en: 'The crossing needs better lighting.', fa: 'محل عبور به روشنایی بهتری نیاز دارد.', pronunciation: 'ذِ کراسینگ نیدز بِتِر لایتینگ', vocabulary: [{ word: 'crossing', meaning: 'محل عبور' }] },
      { id: 'road-slow', en: 'Drivers should slow down near schools.', fa: 'رانندگان باید نزدیک مدارس سرعت را کم کنند.', pronunciation: 'دِرایوِرز شود اِسلو داون نیر اِسکولز', vocabulary: [{ word: 'slow down', meaning: 'کم‌کردن سرعت' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What is the biggest danger here?', fa: 'بزرگ‌ترین خطر اینجا چیست؟' },
      { speaker: 'learner', text: 'Reckless driving puts every pedestrian at risk.', fa: 'رانندگی بی‌پروا هر عابری را در خطر قرار می‌دهد.' },
      { speaker: 'partner', text: 'What is an economical solution?', fa: 'راه‌حل اقتصادی چیست؟' },
      { speaker: 'learner', text: 'Improve public transport and add better lighting.', fa: 'حمل‌ونقل عمومی و روشنایی را بهتر کنیم.' },
    ],
  },
  {
    id: 'advanced-planning-a-community-event', levelId: 4, order: 38,
    title: 'برنامه‌ریزی رویداد محلی', subtitle: 'برآورد هزینه و انتخاب منابع',
    situation: 'برای یک رویداد محلی بودجه و تعداد وسایل لازم را تخمین می‌زنید و خبر خوبی درباره کمک‌ها دریافت می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'event-budget', en: 'Our budget is limited this year.', fa: 'بودجه ما امسال محدود است.', pronunciation: 'آور باجِت ایز لیمیتِد ذیس ییر', vocabulary: [{ word: 'budget', meaning: 'بودجه', essential504: true }] },
      { id: 'event-calculate', en: 'We need to calculate the total cost.', fa: 'باید هزینه کل را محاسبه کنیم.', pronunciation: 'وی نید تو کَلکیولِیت ذِ توتِل کاست', vocabulary: [{ word: 'calculate', meaning: 'محاسبه کردن', essential504: true }] },
      { id: 'event-estimate', en: 'Can you estimate how many people will attend?', fa: 'می‌توانید تخمین بزنید چند نفر شرکت می‌کنند؟', pronunciation: 'کَن یو اِستِمِیت هاو مِنی پیپِل ویل اَتِند؟', vocabulary: [{ word: 'estimate', meaning: 'تخمین زدن', essential504: true }] },
      { id: 'event-fortunate', en: 'We are fortunate to have local support.', fa: 'خوش‌شانسیم که حمایت محلی داریم.', pronunciation: 'وی آر فورچِنِت تو هَو لوکِل ساپورت', vocabulary: [{ word: 'fortunate', meaning: 'خوش‌شانس', essential504: true }] },
      { id: 'event-donate', en: 'Two stores agreed to donate food.', fa: 'دو فروشگاه پذیرفتند غذا اهدا کنند.', pronunciation: 'تو اِستورز اَگرید تو دونِیت فود', vocabulary: [{ word: 'donate', meaning: 'اهدا کردن' }] },
      { id: 'event-list', en: 'Let us make a list of what we still need.', fa: 'بیایید فهرستی از چیزهایی که هنوز لازم داریم تهیه کنیم.', pronunciation: 'لِت آس مِیک اَ لیست آو وات وی اِستیل نید', vocabulary: [{ word: 'list', meaning: 'فهرست' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Can you estimate the number of guests?', fa: 'می‌توانید تعداد مهمانان را تخمین بزنید؟' },
      { speaker: 'learner', text: 'Yes. Then we can calculate the total cost.', fa: 'بله. بعد می‌توانیم هزینه کل را محاسبه کنیم.' },
      { speaker: 'partner', text: 'Our budget is limited.', fa: 'بودجه ما محدود است.' },
      { speaker: 'learner', text: 'We are fortunate to have support from local stores.', fa: 'خوش‌شانسیم که فروشگاه‌های محلی حمایت می‌کنند.' },
    ],
  },
  {
    id: 'advanced-visiting-a-heritage-site', levelId: 4, order: 39,
    title: 'بازدید از مکان تاریخی', subtitle: 'رفتار مناسب و توصیف محیط',
    situation: 'از یک مکان تاریخی مهم بازدید می‌کنید و راهنما درباره ارزش، وسعت و قوانین آن توضیح می‌دهد.', durationMinutes: 13,
    sentences: [
      { id: 'heritage-sacred', en: 'This room is sacred to the local community.', fa: 'این اتاق برای جامعه محلی مقدس است.', pronunciation: 'ذیس روم ایز سِیکرِد تو ذِ لوکِل کِمیونِتی', vocabulary: [{ word: 'sacred', meaning: 'مقدس', essential504: true }] },
      { id: 'heritage-casual', en: 'Casual behavior may be inappropriate here.', fa: 'رفتار بیش از حد خودمانی ممکن است اینجا نامناسب باشد.', pronunciation: 'کَژوئِل بِهِیویر مِی بی اِنَپروپریِت هیر', vocabulary: [{ word: 'casual', meaning: 'خودمانی / غیررسمی', essential504: true }] },
      { id: 'heritage-vast', en: 'The site covers a vast area.', fa: 'این مکان محدوده بسیار وسیعی را پوشش می‌دهد.', pronunciation: 'ذِ سایت کاوِرز اَ وَست اِریا', vocabulary: [{ word: 'vast', meaning: 'وسیع / پهناور', essential504: true }] },
      { id: 'heritage-abundant', en: 'The museum contains abundant historical evidence.', fa: 'موزه شواهد تاریخی فراوانی دارد.', pronunciation: 'ذِ میوزیِم کِنتِینز اَباندِنت هیستوریکِل اِویدِنس', vocabulary: [{ word: 'abundant', meaning: 'فراوان', essential504: true }] },
      { id: 'heritage-photo', en: 'Photography is not allowed in this room.', fa: 'عکاسی در این اتاق مجاز نیست.', pronunciation: 'فِتاگِرَفی ایز نات اَلَود این ذیس روم', vocabulary: [{ word: 'allowed', meaning: 'مجاز' }] },
      { id: 'heritage-respect', en: 'Please speak quietly and show respect.', fa: 'لطفاً آرام صحبت کنید و احترام بگذارید.', pronunciation: 'پلیز اِسپیک کوایِتلی اَند شو ریسپِکت', vocabulary: [{ word: 'respect', meaning: 'احترام' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why must we speak quietly?', fa: 'چرا باید آرام صحبت کنیم؟' },
      { speaker: 'learner', text: 'This room is sacred to the local community.', fa: 'این اتاق برای جامعه محلی مقدس است.' },
      { speaker: 'partner', text: 'Is the historical site large?', fa: 'مکان تاریخی بزرگ است؟' },
      { speaker: 'learner', text: 'Yes, it covers a vast area and contains abundant evidence.', fa: 'بله، بسیار وسیع است و شواهد فراوانی دارد.' },
    ],
  },
];
