import type { SentenceLesson } from './courseContent';

/** Seventh original content pack: 32 verified words from the 504 list. */
export const ADVANCED_SENTENCE_LESSONS_6: SentenceLesson[] = [
  {
    id: 'advanced-discussing-building-rules', levelId: 4, order: 56,
    title: 'گفت‌وگو درباره قوانین ساختمان', subtitle: 'تغییر قانون قدیمی و احترام به مقررات',
    situation: 'ساکنان یک ساختمان قدیمی درباره قوانین مشترک و حذف یک قانون غیرضروری جلسه دارند.', durationMinutes: 13,
    sentences: [
      { id: 'building-abide', en: 'All residents must abide by the safety rules.', fa: 'همه ساکنان باید قوانین ایمنی را رعایت کنند.', pronunciation: 'آل رِزیدِنتس ماست اَباید بای ذِ سِیفْتی رولز', vocabulary: [{ word: 'abide', meaning: 'پایبند بودن / رعایت کردن', essential504: true }] },
      { id: 'building-abolish', en: 'The residents voted to abolish the old rule.', fa: 'ساکنان رأی دادند قانون قدیمی حذف شود.', pronunciation: 'ذِ رِزیدِنتس ووتِد تو اَبالیش ذی اُلد رول', vocabulary: [{ word: 'abolish', meaning: 'لغو و حذف کردن', essential504: true }] },
      { id: 'building-bachelor', en: 'A young bachelor moved into the third floor.', fa: 'یک مرد جوان مجرد به طبقه سوم نقل مکان کرد.', pronunciation: 'اَ یانگ بَچِلِر موود اینتو ذِ ثِرد فِلور', vocabulary: [{ word: 'bachelor', meaning: 'مرد مجرد', essential504: true }] },
      { id: 'building-century', en: 'The building is more than a century old.', fa: 'ساختمان بیش از یک قرن قدمت دارد.', pronunciation: 'ذِ بیلدینگ ایز مور ذَن اَ سِنچِری اُلد', vocabulary: [{ word: 'century', meaning: 'قرن / صد سال', essential504: true }] },
      { id: 'building-noise', en: 'Please keep noise low after ten.', fa: 'لطفاً بعد از ساعت ده سروصدا را کم کنید.', pronunciation: 'پلیز کیپ نویز لو اَفتِر تِن', vocabulary: [{ word: 'noise', meaning: 'سروصدا' }] },
      { id: 'building-repair', en: 'The stairs need an urgent repair.', fa: 'پله‌ها به تعمیر فوری نیاز دارند.', pronunciation: 'ذِ اِسترز نید اَن اِرجِنت ریپِر', vocabulary: [{ word: 'repair', meaning: 'تعمیر' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why should we abolish this rule?', fa: 'چرا باید این قانون را حذف کنیم؟' },
      { speaker: 'learner', text: 'It is outdated, but everyone must still abide by the safety rules.', fa: 'قدیمی است، اما همه همچنان باید قوانین ایمنی را رعایت کنند.' },
      { speaker: 'partner', text: 'This building is very old.', fa: 'این ساختمان خیلی قدیمی است.' },
      { speaker: 'learner', text: 'Yes, it is more than a century old.', fa: 'بله، بیش از یک قرن قدمت دارد.' },
    ],
  },
  {
    id: 'advanced-building-healthy-digital-habits', levelId: 4, order: 57,
    title: 'ساخت عادت دیجیتال سالم', subtitle: 'کم‌کردن وابستگی و فشار اجتماعی',
    situation: 'با خانواده درباره استفاده نوجوانان از شبکه‌های اجتماعی و ساختن عادت‌های سالم صحبت می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'digital-addict', en: 'Some apps can addict users to constant updates.', fa: 'بعضی برنامه‌ها می‌توانند کاربران را به به‌روزرسانی مداوم وابسته کنند.', pronunciation: 'سام اَپس کَن اَدیکت یوزِرز تو کانستِنت آپدِیتس', vocabulary: [{ word: 'addict', meaning: 'وابسته‌کردن', essential504: true }] },
      { id: 'digital-adolescent', en: 'An adolescent may be sensitive to online pressure.', fa: 'یک نوجوان ممکن است نسبت به فشار آنلاین حساس باشد.', pronunciation: 'اَن اَدِلِسِنت مِی بی سِنسیتیو تو آنلاین پِرِشِر', vocabulary: [{ word: 'adolescent', meaning: 'نوجوان', essential504: true }] },
      { id: 'digital-attract', en: 'Bright notifications attract our attention.', fa: 'اعلان‌های روشن توجه ما را جلب می‌کنند.', pronunciation: 'بِرایت نوتیفیکِیشِنز اَترَکت آور اَتِنشِن', vocabulary: [{ word: 'attract', meaning: 'جذب کردن', essential504: true }] },
      { id: 'digital-awkward', en: 'The first family conversation may feel awkward.', fa: 'اولین گفت‌وگوی خانوادگی ممکن است کمی معذب‌کننده باشد.', pronunciation: 'ذِ فِرست فَمِلی کانْوِرسِیشِن مِی فیل آکوِرد', vocabulary: [{ word: 'awkward', meaning: 'معذب‌کننده / ناشیانه', essential504: true }] },
      { id: 'digital-limit', en: 'Set a quiet hour before sleep.', fa: 'یک ساعت آرام پیش از خواب تعیین کنید.', pronunciation: 'سِت اَ کوایِت آور بیفور اِسلیپ', vocabulary: [{ word: 'quiet hour', meaning: 'ساعت بدون مزاحمت' }] },
      { id: 'digital-example', en: 'Adults should follow the same rules.', fa: 'بزرگسالان هم باید همان قوانین را رعایت کنند.', pronunciation: 'اَدالتس شود فالو ذِ سِیم رولز', vocabulary: [{ word: 'adult', meaning: 'بزرگسال' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why do notifications attract us so easily?', fa: 'چرا اعلان‌ها این‌قدر راحت ما را جذب می‌کنند؟' },
      { speaker: 'learner', text: 'They are designed to keep us checking for updates.', fa: 'طراحی شده‌اند تا مرتب به‌روزرسانی‌ها را بررسی کنیم.' },
      { speaker: 'partner', text: 'How can we help an adolescent?', fa: 'چطور به نوجوان کمک کنیم؟' },
      { speaker: 'learner', text: 'Have an honest conversation, even if it feels awkward.', fa: 'گفت‌وگویی صادقانه داشته باشیم، حتی اگر معذب‌کننده باشد.' },
    ],
  },
  {
    id: 'advanced-selecting-a-team-leader', levelId: 4, order: 58,
    title: 'انتخاب سرپرست تیم', subtitle: 'بررسی نامزدها و قدردانی از همکار',
    situation: 'تیم شما باید فرد مناسبی را برای مدیریت یک پروژه انتخاب و مسئولیت او را رسمی کند.', durationMinutes: 13,
    sentences: [
      { id: 'leader-appoint', en: 'The director will appoint a new team leader.', fa: 'مدیر یک سرپرست جدید برای تیم منصوب می‌کند.', pronunciation: 'ذِ دایرِکتِر ویل اَپوینت اَ نیو تیم لیدِر', vocabulary: [{ word: 'appoint', meaning: 'منصوب کردن', essential504: true }] },
      { id: 'leader-candidate', en: 'Each candidate will present a short plan.', fa: 'هر نامزد یک برنامه کوتاه ارائه می‌دهد.', pronunciation: 'ایچ کَندیدِیت ویل پریزِنت اَ شورت پِلَن', vocabulary: [{ word: 'candidate', meaning: 'نامزد', essential504: true }] },
      { id: 'leader-commend', en: 'I commend Sara for her honest work.', fa: 'سارا را به‌خاطر کار صادقانه‌اش تحسین می‌کنم.', pronunciation: 'آی کِمِند سارا فُر هِر آنِست وِرک', vocabulary: [{ word: 'commend', meaning: 'تحسین کردن', essential504: true }] },
      { id: 'leader-colleague', en: 'A trusted colleague recommended her.', fa: 'یک همکار مورداعتماد او را پیشنهاد کرد.', pronunciation: 'اَ تِرَستِد کالیگ رِکِمِندِد هِر', vocabulary: [{ word: 'colleague', meaning: 'همکار', essential504: true }] },
      { id: 'leader-fair', en: 'The selection process must be fair.', fa: 'فرایند انتخاب باید عادلانه باشد.', pronunciation: 'ذِ سِلِکشِن پراسِس ماست بی فِر', vocabulary: [{ word: 'selection process', meaning: 'فرایند انتخاب' }] },
      { id: 'leader-result', en: 'We will announce the result tomorrow.', fa: 'نتیجه را فردا اعلام می‌کنیم.', pronunciation: 'وی ویل اَناونس ذِ ریزالت تومارو', vocabulary: [{ word: 'announce', meaning: 'اعلام کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Who will appoint the team leader?', fa: 'چه کسی سرپرست تیم را منصوب می‌کند؟' },
      { speaker: 'learner', text: 'The director, after every candidate presents a plan.', fa: 'مدیر، پس از ارائه برنامه توسط هر نامزد.' },
      { speaker: 'partner', text: 'Who do you recommend?', fa: 'چه کسی را پیشنهاد می‌کنید؟' },
      { speaker: 'learner', text: 'I commend my colleague Sara for her honest work.', fa: 'همکارم سارا را برای کار صادقانه‌اش تحسین می‌کنم.' },
    ],
  },
  {
    id: 'advanced-preparing-for-a-fishing-trip', levelId: 4, order: 59,
    title: 'آمادگی برای ماهیگیری', subtitle: 'برداشتن وسایل لازم و رعایت احتیاط',
    situation: 'برای یک سفر کوتاه ماهیگیری آماده می‌شوید و درباره وسایل و نکات ایمنی تصمیم می‌گیرید.', durationMinutes: 13,
    sentences: [
      { id: 'fishing-bait', en: 'We need fresh bait for the fishing trip.', fa: 'برای سفر ماهیگیری به طعمه تازه نیاز داریم.', pronunciation: 'وی نید فِرِش بِیت فُر ذِ فیشینگ تِریپ', vocabulary: [{ word: 'bait', meaning: 'طعمه', essential504: true }] },
      { id: 'fishing-beckon', en: 'Sam beckoned us to come closer to the river.', fa: 'سام با اشاره از ما خواست به رودخانه نزدیک‌تر شویم.', pronunciation: 'سَم بِکِند آس تو کام کِلوسِر تو ذِ ریوِر', vocabulary: [{ word: 'beckon', meaning: 'با اشاره فراخواندن', essential504: true }] },
      { id: 'fishing-bulky', en: 'This bulky cooler is difficult to carry.', fa: 'حمل این یخدان بزرگ و جاگیر دشوار است.', pronunciation: 'ذیس بالکی کولِر ایز دیفیکِلت تو کَری', vocabulary: [{ word: 'bulky', meaning: 'بزرگ و جاگیر', essential504: true }] },
      { id: 'fishing-caution', en: 'Use caution near the wet rocks.', fa: 'نزدیک سنگ‌های خیس احتیاط کنید.', pronunciation: 'یوز کاشِن نیر ذِ وِت راکس', vocabulary: [{ word: 'caution', meaning: 'احتیاط' }] },
      { id: 'fishing-keg', en: 'We packed drinking water in a small keg.', fa: 'آب آشامیدنی را در یک بشکه کوچک گذاشتیم.', pronunciation: 'وی پَکت دِرینکینگ واتِر این اَ اِسمال کِگ', vocabulary: [{ word: 'keg', meaning: 'بشکه کوچک', essential504: true }] },
      { id: 'fishing-return', en: 'We will return before sunset.', fa: 'پیش از غروب برمی‌گردیم.', pronunciation: 'وی ویل ریتِرن بیفور سان‌سِت', vocabulary: [{ word: 'sunset', meaning: 'غروب' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Do we have fresh bait?', fa: 'طعمه تازه داریم؟' },
      { speaker: 'learner', text: 'Yes, but this bulky cooler is hard to carry.', fa: 'بله، اما حمل این یخدان جاگیر سخت است.' },
      { speaker: 'partner', text: 'Sam is beckoning us toward the river.', fa: 'سام با اشاره ما را به سمت رودخانه می‌خواند.' },
      { speaker: 'learner', text: 'Use caution. The rocks are wet.', fa: 'احتیاط کن. سنگ‌ها خیس‌اند.' },
    ],
  },
  {
    id: 'advanced-discussing-a-biography', levelId: 4, order: 60,
    title: 'گفت‌وگو درباره زندگی‌نامه', subtitle: 'تحلیل تصمیم و اشتباه یک شخصیت',
    situation: 'در گروه مطالعه درباره زندگی‌نامه یک شخصیت تاریخی و تصمیم‌های دشوار او صحبت می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'biography-biography', en: 'This biography covers her early life and career.', fa: 'این زندگی‌نامه دوران کودکی و حرفه او را پوشش می‌دهد.', pronunciation: 'ذیس بای‌آگْرَفی کاوِرز هِر اِرلی لایف اَند کِریِر', vocabulary: [{ word: 'biography', meaning: 'زندگی‌نامه', essential504: true }] },
      { id: 'biography-betray', en: 'Her closest adviser chose to betray her.', fa: 'نزدیک‌ترین مشاورش تصمیم گرفت به او خیانت کند.', pronunciation: 'هِر کِلوسِست اَدوایزِر چوز تو بِتْرِی هِر', vocabulary: [{ word: 'betray', meaning: 'خیانت کردن', essential504: true }] },
      { id: 'biography-bewildered', en: 'She was bewildered by the sudden change.', fa: 'او از تغییر ناگهانی کاملاً سردرگم شد.', pronunciation: 'شی واز بِویلْدِرد بای ذِ سادِن چِینج', vocabulary: [{ word: 'bewildered', meaning: 'کاملاً سردرگم', essential504: true }] },
      { id: 'biography-blunder', en: 'One political blunder damaged her reputation.', fa: 'یک اشتباه سیاسی به اعتبار او آسیب زد.', pronunciation: 'وان پِلیتیکِل بِلاندِر دَمِجد هِر رِپیوتِیشِن', vocabulary: [{ word: 'blunder', meaning: 'اشتباه بزرگ و شرم‌آور', essential504: true }] },
      { id: 'biography-context', en: 'We should understand the historical context.', fa: 'باید زمینه تاریخی را درک کنیم.', pronunciation: 'وی شود آندِراِستَند ذِ هیستوریکِل کانتِکست', vocabulary: [{ word: 'historical context', meaning: 'زمینه تاریخی' }] },
      { id: 'biography-lesson', en: 'Her mistakes still offer a useful lesson.', fa: 'اشتباهات او هنوز درس مفیدی ارائه می‌دهند.', pronunciation: 'هِر میستِیکس اِستیل آفِر اَ یوسفول لِسِن', vocabulary: [{ word: 'reputation', meaning: 'اعتبار و شهرت' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why was she bewildered?', fa: 'چرا او سردرگم شد؟' },
      { speaker: 'learner', text: 'Her closest adviser chose to betray her.', fa: 'نزدیک‌ترین مشاورش به او خیانت کرد.' },
      { speaker: 'partner', text: 'Did she make mistakes too?', fa: 'خودش هم اشتباه کرد؟' },
      { speaker: 'learner', text: 'Yes. One serious blunder damaged her reputation.', fa: 'بله. یک اشتباه جدی به اعتبارش آسیب زد.' },
    ],
  },
  {
    id: 'advanced-preventing-a-public-fight', levelId: 4, order: 61,
    title: 'جلوگیری از درگیری عمومی', subtitle: 'توقف خشونت و درخواست کمک',
    situation: 'در یک رویداد عمومی بحثی به درگیری تبدیل شده و باید بدون به‌خطرانداختن خودتان کمک بگیرید.', durationMinutes: 13,
    sentences: [
      { id: 'fight-brawl', en: 'A noisy brawl started near the entrance.', fa: 'یک درگیری پرسروصدا نزدیک ورودی شروع شد.', pronunciation: 'اَ نویزی بِرال اِستارتِد نیر ذی اِنترِنس', vocabulary: [{ word: 'brawl', meaning: 'درگیری و دعوای پرسروصدا', essential504: true }] },
      { id: 'fight-brutal', en: 'The brutal attack left several people injured.', fa: 'حمله خشونت‌آمیز چند نفر را مجروح کرد.', pronunciation: 'ذِ بروتِل اَتَک لِفت سِوِرِل پیپِل اینجِرد', vocabulary: [{ word: 'brutal', meaning: 'بی‌رحمانه / خشن', essential504: true }] },
      { id: 'fight-abuse', en: 'Verbal abuse can quickly increase tension.', fa: 'توهین کلامی می‌تواند تنش را سریع افزایش دهد.', pronunciation: 'وِربِل اَبیوس کَن کوییکلی اینکریس تِنشِن', vocabulary: [{ word: 'abuse', meaning: 'بدرفتاری / توهین', essential504: true }] },
      { id: 'fight-cease', en: 'The fighting must cease immediately.', fa: 'درگیری باید فوراً متوقف شود.', pronunciation: 'ذِ فایتینگ ماست سیس ایمیدیِتلی', vocabulary: [{ word: 'cease', meaning: 'متوقف شدن', essential504: true }] },
      { id: 'fight-distance', en: 'Keep a safe distance and call security.', fa: 'فاصله امن را حفظ کنید و با مأموران امنیت تماس بگیرید.', pronunciation: 'کیپ اَ سِیف دیستِنس اَند کال سِکیورِتی', vocabulary: [{ word: 'safe distance', meaning: 'فاصله امن' }] },
      { id: 'fight-witness', en: 'Tell the staff exactly what you witnessed.', fa: 'دقیقاً چیزی را که دیدید به کارکنان بگویید.', pronunciation: 'تِل ذِ اِستَف اِگزَکتلی وات یو ویتنِست', vocabulary: [{ word: 'witness', meaning: 'شاهد بودن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Should we try to stop the brawl ourselves?', fa: 'خودمان دعوا را متوقف کنیم؟' },
      { speaker: 'learner', text: 'No. Keep a safe distance and call security.', fa: 'نه. فاصله امن را حفظ کن و با امنیت تماس بگیر.' },
      { speaker: 'partner', text: 'What should we report?', fa: 'چه چیزی را گزارش کنیم؟' },
      { speaker: 'learner', text: 'Report the verbal abuse and brutal attack you witnessed.', fa: 'توهین و حمله خشنی را که دیدی گزارش کن.' },
    ],
  },
  {
    id: 'advanced-discussing-media-and-charity', levelId: 4, order: 62,
    title: 'رسانه و فعالیت خیریه', subtitle: 'بررسی محدودیت و نقش گروه‌های اجتماعی',
    situation: 'درباره یک فیلم خیریه و تصمیم حذف بخشی از آن پیش از نمایش عمومی بحث می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'media-censor', en: 'Officials tried to censor part of the film.', fa: 'مسئولان تلاش کردند بخشی از فیلم را سانسور کنند.', pronunciation: 'اُفیشِلز تِراید تو سِنسِر پارت آو ذِ فیلم', vocabulary: [{ word: 'censor', meaning: 'سانسور کردن', essential504: true }] },
      { id: 'media-cinema', en: 'The documentary will appear in local cinemas.', fa: 'مستند در سینماهای محلی نمایش داده می‌شود.', pronunciation: 'ذِ داکیومِنتِری ویل اَپیر این لوکِل سینِماز', vocabulary: [{ word: 'cinema', meaning: 'سینما', essential504: true }] },
      { id: 'media-charity', en: 'Ticket sales will support a children’s charity.', fa: 'فروش بلیط از یک مؤسسه خیریه کودکان حمایت می‌کند.', pronunciation: 'تیکِت سِیلز ویل ساپورت اَ چیلدْرِنز چَرِتی', vocabulary: [{ word: 'charity', meaning: 'مؤسسه خیریه', essential504: true }] },
      { id: 'media-clergy', en: 'Local clergy joined the public discussion.', fa: 'روحانیان محلی به گفت‌وگوی عمومی پیوستند.', pronunciation: 'لوکِل کِلِرجی جویند ذِ پابلیک دیسکاشِن', vocabulary: [{ word: 'clergy', meaning: 'روحانیان', essential504: true }] },
      { id: 'media-view', en: 'Viewers should hear more than one opinion.', fa: 'بینندگان باید بیش از یک دیدگاه را بشنوند.', pronunciation: 'ویوِرز شود هیر مور ذَن وان اَپینیِن', vocabulary: [{ word: 'viewer', meaning: 'بیننده' }] },
      { id: 'media-donate', en: 'You can donate without buying a ticket.', fa: 'می‌توانید بدون خرید بلیط کمک مالی کنید.', pronunciation: 'یو کَن دونِیت ویداوت بایینگ اَ تیکِت', vocabulary: [{ word: 'donate', meaning: 'کمک مالی کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why did officials censor the film?', fa: 'چرا مسئولان فیلم را سانسور کردند؟' },
      { speaker: 'learner', text: 'They disagreed with part of its message.', fa: 'با بخشی از پیام آن مخالف بودند.' },
      { speaker: 'partner', text: 'Where can we watch it?', fa: 'کجا می‌توانیم آن را ببینیم؟' },
      { speaker: 'learner', text: 'In local cinemas. Ticket sales support a charity.', fa: 'در سینماهای محلی. فروش بلیط از خیریه حمایت می‌کند.' },
    ],
  },
  {
    id: 'advanced-improving-a-school-program', levelId: 4, order: 63,
    title: 'بهبود برنامه آموزشی', subtitle: 'رقابت سالم و جلوگیری از رضایت کاذب',
    situation: 'مدیران مدرسه درباره کیفیت برنامه، میزان درک دانش‌آموزان و شکل مناسب رقابت صحبت می‌کنند.', durationMinutes: 14,
    sentences: [
      { id: 'school-coeducational', en: 'The new program is coeducational.', fa: 'برنامه جدید برای دختران و پسران به‌صورت مشترک است.', pronunciation: 'ذِ نیو پروگرام ایز کوئِجوکِیشِنِل', vocabulary: [{ word: 'coeducational', meaning: 'آموزش مشترک دختران و پسران', essential504: true }] },
      { id: 'school-comprehend', en: 'Students must comprehend the idea, not just memorize it.', fa: 'دانش‌آموزان باید مفهوم را درک کنند، نه اینکه فقط حفظ کنند.', pronunciation: 'اِستیودِنتس ماست کامپریهِند ذی آیدیا، نات جاست مِمِرایز ایت', vocabulary: [{ word: 'comprehend', meaning: 'درک کردن', essential504: true }] },
      { id: 'school-compete', en: 'Teams can compete without disrespecting each other.', fa: 'تیم‌ها می‌توانند بدون بی‌احترامی با هم رقابت کنند.', pronunciation: 'تیمز کَن کِمپیت ویداوت دیسریسپِکتینگ ایچ آذِر', vocabulary: [{ word: 'compete', meaning: 'رقابت کردن', essential504: true }] },
      { id: 'school-complacent', en: 'Good results should not make us complacent.', fa: 'نتایج خوب نباید ما را دچار رضایت کاذب کنند.', pronunciation: 'گود ریزالتس شود نات مِیک آس کِمپِلِیسِنت', vocabulary: [{ word: 'complacent', meaning: 'بیش‌ازحد راضی و بی‌خیال', essential504: true }] },
      { id: 'school-feedback', en: 'Ask students for honest feedback.', fa: 'از دانش‌آموزان بازخورد صادقانه بخواهید.', pronunciation: 'اَسک اِستیودِنتس فُر آنِست فیدبَک', vocabulary: [{ word: 'feedback', meaning: 'بازخورد' }] },
      { id: 'school-adjust', en: 'Adjust the lesson when many students are confused.', fa: 'وقتی دانش‌آموزان زیادی سردرگم‌اند، درس را تغییر دهید.', pronunciation: 'اَجاست ذِ لِسِن وِن مِنی اِستیودِنتس آر کِنفیوزد', vocabulary: [{ word: 'adjust', meaning: 'تنظیم و اصلاح کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Are students memorizing or comprehending?', fa: 'دانش‌آموزان حفظ می‌کنند یا درک می‌کنند؟' },
      { speaker: 'learner', text: 'We need better questions to see if they comprehend the ideas.', fa: 'به سؤال‌های بهتری نیاز داریم تا میزان درکشان را ببینیم.' },
      { speaker: 'partner', text: 'Our results are already good.', fa: 'نتایج ما همین حالا هم خوب است.' },
      { speaker: 'learner', text: 'We should not become complacent. We can still improve.', fa: 'نباید دچار رضایت کاذب شویم. هنوز می‌توانیم بهتر شویم.' },
    ],
  },
];
