import type { SentenceLesson } from './courseContent';

/** Third original content pack: 32 more essential words in sentence-first lessons. */
export const ADVANCED_SENTENCE_LESSONS_2: SentenceLesson[] = [
  {
    id: 'advanced-reporting-a-neighborhood-incident', levelId: 4, order: 24,
    title: 'گزارش یک اتفاق محلی', subtitle: 'توضیح دقیق آنچه رخ داده است',
    situation: 'اتفاقی در نزدیکی محل زندگی‌تان افتاده و باید اطلاعاتی روشن و دقیق به مسئول مربوط بدهید.', durationMinutes: 13,
    sentences: [
      { id: 'incident-vicinity', en: 'The incident happened in the vicinity of the station.', fa: 'این اتفاق در نزدیکی ایستگاه رخ داد.', pronunciation: 'ذی اینسیدِنت هَپِند این ذِ وِسینِتی آو ذِ اِستِیشِن', vocabulary: [{ word: 'vicinity', meaning: 'نزدیکی / اطراف', essential504: true }] },
      { id: 'incident-document', en: 'Please document everything you observed.', fa: 'لطفاً هر چیزی را که مشاهده کردید ثبت کنید.', pronunciation: 'پلیز داکیومِنت اِوری‌ثینگ یو آبزِرود', vocabulary: [{ word: 'document', meaning: 'ثبت و مستند کردن', essential504: true }] },
      { id: 'incident-conclude', en: 'It is too early to conclude what happened.', fa: 'برای نتیجه‌گیری درباره اتفاق هنوز خیلی زود است.', pronunciation: 'ایت ایز تو اِرلی تو کِنکلود وات هَپِند', vocabulary: [{ word: 'conclude', meaning: 'نتیجه‌گیری کردن', essential504: true }] },
      { id: 'incident-resist', en: 'Resist the urge to share unconfirmed details.', fa: 'در برابر انتشار جزئیات تأییدنشده مقاومت کنید.', pronunciation: 'ریزیست ذی اِرج تو شِر آنکِنفِرمد دیتِیلز', vocabulary: [{ word: 'resist', meaning: 'مقاومت کردن', essential504: true }] },
      { id: 'incident-time', en: 'I arrived at about eight o’clock.', fa: 'حدود ساعت هشت رسیدم.', pronunciation: 'آی اَرایود اَت اَباوت اِیت اُکلاک', vocabulary: [{ word: 'arrive', meaning: 'رسیدن' }] },
      { id: 'incident-contact', en: 'You can contact me if you need more information.', fa: 'اگر اطلاعات بیشتری لازم بود می‌توانید با من تماس بگیرید.', pronunciation: 'یو کَن کانتَکت می ایف یو نید مور اینفِرمِیشِن', vocabulary: [{ word: 'contact', meaning: 'تماس گرفتن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Where did the incident happen?', fa: 'اتفاق کجا رخ داد؟' },
      { speaker: 'learner', text: 'It happened in the vicinity of the station.', fa: 'در نزدیکی ایستگاه رخ داد.' },
      { speaker: 'partner', text: 'Can we conclude what caused it?', fa: 'می‌توانیم درباره علت نتیجه‌گیری کنیم؟' },
      { speaker: 'learner', text: 'Not yet. We should document the facts first.', fa: 'هنوز نه. ابتدا باید واقعیت‌ها را ثبت کنیم.' },
    ],
  },
  {
    id: 'advanced-building-a-career-plan', levelId: 4, order: 25,
    title: 'ساختن برنامه شغلی', subtitle: 'شناخت عادت‌ها و منابع پیشرفت',
    situation: 'با یک مشاور درباره هدف شغلی خود صحبت می‌کنید و راهی عملی برای پیشرفت می‌سازید.', durationMinutes: 13,
    sentences: [
      { id: 'career-challenge', en: 'My biggest challenge is managing my time.', fa: 'بزرگ‌ترین چالش من مدیریت زمان است.', pronunciation: 'مای بیگِست چَلِنج ایز مَنِجینگ مای تایم', vocabulary: [{ word: 'challenge', meaning: 'چالش', essential504: true }] },
      { id: 'career-source', en: 'This course is a useful source of information.', fa: 'این دوره منبع مفیدی برای اطلاعات است.', pronunciation: 'ذیس کورس ایز اَ یوسفول سورس آو اینفِرمِیشِن', vocabulary: [{ word: 'source', meaning: 'منبع', essential504: true }] },
      { id: 'career-flexible', en: 'I need a flexible study schedule.', fa: 'به یک برنامه مطالعه انعطاف‌پذیر نیاز دارم.', pronunciation: 'آی نید اَ فِلِکسِبِل اِستادی اِسکِجول', vocabulary: [{ word: 'flexible', meaning: 'انعطاف‌پذیر', essential504: true }] },
      { id: 'career-tendency', en: 'I have a tendency to delay difficult tasks.', fa: 'تمایل دارم کارهای دشوار را به تأخیر بیندازم.', pronunciation: 'آی هَو اَ تِندِنسی تو دِلِی دیفیکِلت تَسکس', vocabulary: [{ word: 'tendency', meaning: 'گرایش / تمایل', essential504: true }] },
      { id: 'career-weekly', en: 'I will set one clear goal each week.', fa: 'هر هفته یک هدف روشن تعیین می‌کنم.', pronunciation: 'آی ویل سِت وان کلیر گول ایچ ویک', vocabulary: [{ word: 'goal', meaning: 'هدف' }] },
      { id: 'career-review', en: 'We can review your progress next month.', fa: 'ماه آینده می‌توانیم پیشرفتتان را بررسی کنیم.', pronunciation: 'وی کَن ریویو یور پراگرِس نِکست مانث', vocabulary: [{ word: 'progress', meaning: 'پیشرفت' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What is your biggest challenge?', fa: 'بزرگ‌ترین چالش شما چیست؟' },
      { speaker: 'learner', text: 'I have a tendency to delay difficult tasks.', fa: 'تمایل دارم کارهای دشوار را عقب بیندازم.' },
      { speaker: 'partner', text: 'Try a flexible schedule and set one weekly goal.', fa: 'یک برنامه انعطاف‌پذیر و یک هدف هفتگی را امتحان کنید.' },
    ],
  },
  {
    id: 'advanced-describing-what-you-saw', levelId: 4, order: 26,
    title: 'توصیف چیزی که دیدید', subtitle: 'گزارش محتاطانه و دقیق یک مشاهده',
    situation: 'شاهد یک اتفاق کوتاه بوده‌اید و تلاش می‌کنید فقط چیزهایی را بگویید که واقعاً دیده‌اید.', durationMinutes: 13,
    sentences: [
      { id: 'witness-evidence', en: 'The camera footage may provide useful evidence.', fa: 'تصاویر دوربین ممکن است شواهد مفیدی ارائه کنند.', pronunciation: 'ذِ کَمِرا فوتِج مِی پروواید یوسفول اِویدِنس', vocabulary: [{ word: 'evidence', meaning: 'شواهد / مدرک', essential504: true }] },
      { id: 'witness-frequent', en: 'Traffic is frequent on this street.', fa: 'رفت‌وآمد در این خیابان زیاد است.', pronunciation: 'تِرَفیک ایز فریکوئِنت آن ذیس اِستریت', vocabulary: [{ word: 'frequent', meaning: 'مکرر / پرتعداد', essential504: true }] },
      { id: 'witness-glimpse', en: 'I caught a glimpse of a red car.', fa: 'برای لحظه‌ای یک خودروی قرمز دیدم.', pronunciation: 'آی کات اَ گِلیمپس آو اَ رِد کار', vocabulary: [{ word: 'glimpse', meaning: 'نگاه کوتاه / دیدن لحظه‌ای', essential504: true }] },
      { id: 'witness-hesitate', en: 'Do not hesitate to correct your statement.', fa: 'برای اصلاح گفته خود تردید نکنید.', pronunciation: 'دو نات هِزیتِیت تو کِرِکت یور اِستِیت‌مِنت', vocabulary: [{ word: 'hesitate', meaning: 'تردید کردن', essential504: true }] },
      { id: 'witness-certain', en: 'I am certain about the color, but not the model.', fa: 'از رنگ مطمئنم، اما از مدل نه.', pronunciation: 'آی اَم سِرتِن اَباوت ذِ کالِر، بات نات ذِ مادِل', vocabulary: [{ word: 'certain', meaning: 'مطمئن' }] },
      { id: 'witness-honest', en: 'I only want to report what I actually saw.', fa: 'فقط می‌خواهم چیزی را گزارش کنم که واقعاً دیدم.', pronunciation: 'آی اونلی وانت تو ریپورت وات آی اَکچوئِلی سا', vocabulary: [{ word: 'actually', meaning: 'واقعاً' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Did you see the car clearly?', fa: 'خودرو را واضح دیدید؟' },
      { speaker: 'learner', text: 'No, I only caught a glimpse of it.', fa: 'نه، فقط لحظه‌ای آن را دیدم.' },
      { speaker: 'partner', text: 'Is there any other evidence?', fa: 'مدرک دیگری وجود دارد؟' },
      { speaker: 'learner', text: 'The camera footage may provide evidence.', fa: 'تصاویر دوربین ممکن است مدرک ارائه کنند.' },
    ],
  },
  {
    id: 'advanced-analyzing-a-story', levelId: 4, order: 27,
    title: 'بررسی یک داستان', subtitle: 'تفکیک واقعیت، خیال و دیدگاه‌ها',
    situation: 'در یک گروه مطالعه درباره داستانی بحث می‌کنید و می‌خواهید پیام و دیدگاه‌های آن را تحلیل کنید.', durationMinutes: 14,
    sentences: [
      { id: 'story-conflict', en: 'The main conflict begins between two families.', fa: 'کشمکش اصلی میان دو خانواده آغاز می‌شود.', pronunciation: 'ذِ مِین کانفلیکت بِگینز بِتوین تو فَمِلیز', vocabulary: [{ word: 'conflict', meaning: 'درگیری / کشمکش', essential504: true }] },
      { id: 'story-minority', en: 'The story is told from the minority’s point of view.', fa: 'داستان از دیدگاه گروه اقلیت روایت می‌شود.', pronunciation: 'ذِ اِستوری ایز تولد فرام ذِ ماینورِتیز پوینت آو ویو', vocabulary: [{ word: 'minority', meaning: 'اقلیت', essential504: true }] },
      { id: 'story-fiction', en: 'It is fiction, but it reflects real problems.', fa: 'داستان تخیلی است، اما مشکلات واقعی را بازتاب می‌دهد.', pronunciation: 'ایت ایز فیکشِن، بات ایت رِفِلِکتس ریل پرابلِمز', vocabulary: [{ word: 'fiction', meaning: 'داستان تخیلی', essential504: true }] },
      { id: 'story-absurd', en: 'At first, the character’s decision seems absurd.', fa: 'در ابتدا تصمیم شخصیت پوچ و غیرمنطقی به نظر می‌رسد.', pronunciation: 'اَت فِرست، ذِ کَرِکتِرز دِسیژِن سیمز اَبسِرد', vocabulary: [{ word: 'absurd', meaning: 'پوچ / غیرمنطقی', essential504: true }] },
      { id: 'story-message', en: 'What message does the writer want to share?', fa: 'نویسنده می‌خواهد چه پیامی منتقل کند؟', pronunciation: 'وات مِسِج داز ذِ رایتر وانت تو شِر؟', vocabulary: [{ word: 'message', meaning: 'پیام' }] },
      { id: 'story-view', en: 'I understand the character’s point of view.', fa: 'دیدگاه شخصیت را درک می‌کنم.', pronunciation: 'آی آندِراِستَند ذِ کَرِکتِرز پوینت آو ویو', vocabulary: [{ word: 'point of view', meaning: 'دیدگاه' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Is this story based on facts?', fa: 'این داستان بر اساس واقعیت است؟' },
      { speaker: 'learner', text: 'No, it is fiction, but it reflects a real conflict.', fa: 'نه، تخیلی است اما یک کشمکش واقعی را بازتاب می‌دهد.' },
      { speaker: 'partner', text: 'Why does the decision seem absurd?', fa: 'چرا تصمیم غیرمنطقی به نظر می‌رسد؟' },
      { speaker: 'learner', text: 'Because we do not understand the character’s point of view at first.', fa: 'چون ابتدا دیدگاه شخصیت را درک نمی‌کنیم.' },
    ],
  },
  {
    id: 'advanced-improving-city-air', levelId: 4, order: 28,
    title: 'بهبود هوای شهر', subtitle: 'گفت‌وگو درباره مشکل و راه‌حل شهری',
    situation: 'در جلسه‌ای درباره آلودگی هوا شرکت کرده‌اید و راه‌های عملی بهبود شرایط شهر را بررسی می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'city-urban', en: 'Air pollution is a serious urban problem.', fa: 'آلودگی هوا یک مشکل جدی شهری است.', pronunciation: 'اِر پِلوشِن ایز اَ سیریِس اِربِن پرابلِم', vocabulary: [{ word: 'urban', meaning: 'شهری', essential504: true }] },
      { id: 'city-population', en: 'The city’s population has grown rapidly.', fa: 'جمعیت شهر به‌سرعت رشد کرده است.', pronunciation: 'ذِ سیتیز پاپیولِیشِن هَز گرون رَپیدلی', vocabulary: [{ word: 'population', meaning: 'جمعیت', essential504: true }] },
      { id: 'city-pollute', en: 'Old vehicles pollute the air.', fa: 'خودروهای قدیمی هوا را آلوده می‌کنند.', pronunciation: 'اُلد ویهِکِلز پِلوت ذی اِر', vocabulary: [{ word: 'pollute', meaning: 'آلوده کردن', essential504: true }] },
      { id: 'city-prohibit', en: 'The city may prohibit cars in this area.', fa: 'ممکن است شهر ورود خودروها به این منطقه را ممنوع کند.', pronunciation: 'ذِ سیتی مِی پروهِبیت کارز این ذیس اِریا', vocabulary: [{ word: 'prohibit', meaning: 'ممنوع کردن', essential504: true }] },
      { id: 'city-transit', en: 'Better public transport can reduce traffic.', fa: 'حمل‌ونقل عمومی بهتر می‌تواند ترافیک را کاهش دهد.', pronunciation: 'بِتِر پابلیک تِرَنسپورت کَن ریدیوس تِرَفیک', vocabulary: [{ word: 'public transport', meaning: 'حمل‌ونقل عمومی' }] },
      { id: 'city-breathe', en: 'Everyone deserves clean air to breathe.', fa: 'همه سزاوار هوای پاک برای تنفس هستند.', pronunciation: 'اِوری‌وان دیزِروز کلین اِر تو بریذ', vocabulary: [{ word: 'breathe', meaning: 'نفس کشیدن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What causes this urban problem?', fa: 'چه چیزی این مشکل شهری را ایجاد می‌کند؟' },
      { speaker: 'learner', text: 'Old vehicles pollute the air, and the population is growing.', fa: 'خودروهای قدیمی هوا را آلوده می‌کنند و جمعیت در حال رشد است.' },
      { speaker: 'partner', text: 'What can the city do?', fa: 'شهر چه کاری می‌تواند انجام دهد؟' },
      { speaker: 'learner', text: 'It can improve public transport and prohibit cars in some areas.', fa: 'می‌تواند حمل‌ونقل عمومی را بهتر و خودروها را در بعضی مناطق ممنوع کند.' },
    ],
  },
  {
    id: 'advanced-making-an-emergency-announcement', levelId: 4, order: 29,
    title: 'اعلام یک هشدار فوری', subtitle: 'انتقال روشن اطلاعات مهم',
    situation: 'در یک ساختمان عمومی باید یک پیام فوری، کوتاه و قابل‌شنیدن برای همه اعلام کنید.', durationMinutes: 13,
    sentences: [
      { id: 'announcement-urgent', en: 'This is an urgent safety announcement.', fa: 'این یک اعلامیه فوری ایمنی است.', pronunciation: 'ذیس ایز اَن اِرجِنت سِیفْتی اَناونس‌مِنت', vocabulary: [{ word: 'urgent', meaning: 'فوری', essential504: true }] },
      { id: 'announcement-adequate', en: 'There is adequate time to leave safely.', fa: 'زمان کافی برای خروج ایمن وجود دارد.', pronunciation: 'ذِر ایز اَدِکویت تایم تو لیو سِیفلی', vocabulary: [{ word: 'adequate', meaning: 'کافی / مناسب', essential504: true }] },
      { id: 'announcement-decrease', en: 'Please decrease your walking speed near the stairs.', fa: 'لطفاً نزدیک پله‌ها سرعت راه‌رفتن را کاهش دهید.', pronunciation: 'پلیز دیکریس یور واکینگ اِسپید نیر ذِ اِسترز', vocabulary: [{ word: 'decrease', meaning: 'کاهش دادن', essential504: true }] },
      { id: 'announcement-audible', en: 'The instructions must be audible to everyone.', fa: 'دستورالعمل‌ها باید برای همه قابل‌شنیدن باشند.', pronunciation: 'ذی اینسترَکشِنز ماست بی آدِبِل تو اِوری‌وان', vocabulary: [{ word: 'audible', meaning: 'قابل‌شنیدن', essential504: true }] },
      { id: 'announcement-exit', en: 'Use the nearest marked exit.', fa: 'از نزدیک‌ترین خروجی علامت‌گذاری‌شده استفاده کنید.', pronunciation: 'یوز ذِ نیرِست مارکت اِگزیت', vocabulary: [{ word: 'exit', meaning: 'خروجی' }] },
      { id: 'announcement-calm', en: 'Remain calm and follow the staff.', fa: 'آرام بمانید و کارکنان را دنبال کنید.', pronunciation: 'ریمِین کام اَند فالو ذِ اِستَف', vocabulary: [{ word: 'remain calm', meaning: 'آرام ماندن' }] },
    ],
    dialogue: [
      { speaker: 'learner', text: 'This is an urgent safety announcement.', fa: 'این یک اعلامیه فوری ایمنی است.' },
      { speaker: 'partner', text: 'Do we have enough time?', fa: 'زمان کافی داریم؟' },
      { speaker: 'learner', text: 'Yes, there is adequate time. Remain calm and use the nearest exit.', fa: 'بله، زمان کافی هست. آرام بمانید و از نزدیک‌ترین خروجی استفاده کنید.' },
    ],
  },
  {
    id: 'advanced-working-in-a-newsroom', levelId: 4, order: 30,
    title: 'کار در تحریریه خبر', subtitle: 'شناسایی واقعیت و پیگیری پاسخ',
    situation: 'خبرنگار و سردبیر در حال بررسی اطلاعات یک گزارش هستند و باید هویت منابع را تأیید کنند.', durationMinutes: 14,
    sentences: [
      { id: 'news-journalist', en: 'A responsible journalist verifies every claim.', fa: 'یک خبرنگار مسئول هر ادعا را بررسی می‌کند.', pronunciation: 'اَ ریسپانْسِبِل جِرنِلیست وِریفایز اِوری کِلِیم', vocabulary: [{ word: 'journalist', meaning: 'خبرنگار', essential504: true }] },
      { id: 'news-identify', en: 'We must identify the original source.', fa: 'باید منبع اصلی را شناسایی کنیم.', pronunciation: 'وی ماست آیدِنتیفای ذی اریجِنِل سورس', vocabulary: [{ word: 'identify', meaning: 'شناسایی کردن', essential504: true }] },
      { id: 'news-persist', en: 'Persist until you receive a clear answer.', fa: 'تا زمانی که پاسخ روشنی بگیرید پیگیری کنید.', pronunciation: 'پِرسیست اَنتیل یو ریسیو اَ کلیر اَنسِر', vocabulary: [{ word: 'persist', meaning: 'ادامه‌دادن / پافشاری کردن', essential504: true }] },
      { id: 'news-editor', en: 'The editor requested stronger evidence.', fa: 'سردبیر شواهد محکم‌تری درخواست کرد.', pronunciation: 'ذی اِدیتِر ریکوئِستِد اِسترانگِر اِویدِنس', vocabulary: [{ word: 'editor', meaning: 'سردبیر / ویراستار', essential504: true }] },
      { id: 'news-publish', en: 'We are not ready to publish the report.', fa: 'هنوز آماده انتشار گزارش نیستیم.', pronunciation: 'وی آر نات رِدی تو پابلیش ذِ ریپورت', vocabulary: [{ word: 'publish', meaning: 'منتشر کردن' }] },
      { id: 'news-fair', en: 'Give both sides a fair chance to respond.', fa: 'به هر دو طرف فرصت عادلانه‌ای برای پاسخ بدهید.', pronunciation: 'گیو بوث سایدز اَ فِر چَنس تو ریسپاند', vocabulary: [{ word: 'fair', meaning: 'عادلانه' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Can we publish this report?', fa: 'می‌توانیم این گزارش را منتشر کنیم؟' },
      { speaker: 'learner', text: 'Not yet. We must identify the source and verify every claim.', fa: 'هنوز نه. باید منبع را شناسایی و هر ادعا را بررسی کنیم.' },
      { speaker: 'partner', text: 'The editor also requested stronger evidence.', fa: 'سردبیر هم شواهد محکم‌تری خواسته است.' },
    ],
  },
  {
    id: 'advanced-improving-a-small-business', levelId: 4, order: 31,
    title: 'بهبود یک کسب‌وکار کوچک', subtitle: 'تغییر، رشد و دنبال‌کردن ایده تازه',
    situation: 'با شریک کاری خود درباره رشد کسب‌وکار و ایجاد یک محصول بهتر گفت‌وگو می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'business-expand', en: 'We plan to expand the business next year.', fa: 'قصد داریم سال آینده کسب‌وکار را گسترش دهیم.', pronunciation: 'وی پِلَن تو اِکسپَند ذِ بیزنِس نِکست ییر', vocabulary: [{ word: 'expand', meaning: 'گسترش دادن', essential504: true }] },
      { id: 'business-alter', en: 'We may need to alter our original plan.', fa: 'ممکن است لازم باشد برنامه اولیه را تغییر دهیم.', pronunciation: 'وی مِی نید تو آلتِر آور اریجِنِل پِلَن', vocabulary: [{ word: 'alter', meaning: 'تغییر دادن', essential504: true }] },
      { id: 'business-pursue', en: 'We should pursue the most promising idea.', fa: 'باید امیدوارکننده‌ترین ایده را دنبال کنیم.', pronunciation: 'وی شود پِرسو ذِ موست پرامیسینگ آیدیا', vocabulary: [{ word: 'pursue', meaning: 'دنبال کردن', essential504: true }] },
      { id: 'business-innovative', en: 'Customers want a simple but innovative product.', fa: 'مشتریان محصولی ساده اما نوآورانه می‌خواهند.', pronunciation: 'کاستِمِرز وانت اَ سیمپِل بات اینِوِیتیو پراداکت', vocabulary: [{ word: 'innovative', meaning: 'نوآورانه', essential504: true }] },
      { id: 'business-budget', en: 'We must stay within our budget.', fa: 'باید در محدوده بودجه بمانیم.', pronunciation: 'وی ماست اِستِی ویدین آور باجِت', vocabulary: [{ word: 'budget', meaning: 'بودجه' }] },
      { id: 'business-test', en: 'Let us test the idea with a small group.', fa: 'بیایید ایده را با یک گروه کوچک آزمایش کنیم.', pronunciation: 'لِت آس تِست ذی آیدیا ویذ اَ اِسمال گروپ', vocabulary: [{ word: 'test', meaning: 'آزمایش کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'How can we expand the business?', fa: 'چطور می‌توانیم کسب‌وکار را گسترش دهیم؟' },
      { speaker: 'learner', text: 'We should pursue an innovative product idea.', fa: 'باید یک ایده محصول نوآورانه را دنبال کنیم.' },
      { speaker: 'partner', text: 'Do we need to alter our plan?', fa: 'لازم است برنامه را تغییر دهیم؟' },
      { speaker: 'learner', text: 'Yes, but we must stay within our budget.', fa: 'بله، اما باید در محدوده بودجه بمانیم.' },
    ],
  },
];
