import type { SentenceLesson } from './courseContent';

/**
 * Original sentence-first lessons that weave selected 504 words into natural
 * situations. They use the exact same six-stage lesson player as every other
 * lesson; no separate vocabulary course is introduced.
 */
export const EXPANDED_SENTENCE_LESSONS: SentenceLesson[] = [
  {
    id: 'everyday-handling-a-misunderstanding',
    levelId: 2,
    order: 8,
    title: 'حل یک سوءتفاهم',
    subtitle: 'صحبت محترمانه درباره احساسات',
    situation: 'از رفتار یکی از دوستانتان ناراحت شده‌اید و می‌خواهید بدون ایجاد دعوا، احساس خود را توضیح دهید.',
    durationMinutes: 12,
    sentences: [
      { id: 'misunderstanding-jealous', en: 'I felt jealous when I saw them together.', fa: 'وقتی آن‌ها را با هم دیدم، حسادت کردم.', pronunciation: 'آی فِلت جِلِس وِن آی سا دِم توگِذِر', vocabulary: [{ word: 'jealous', meaning: 'حسود / دچار حسادت', essential504: true }] },
      { id: 'misunderstanding-tact', en: 'We should discuss this with tact.', fa: 'باید با ملاحظه درباره این موضوع صحبت کنیم.', pronunciation: 'وی شود دیسکاس ذیس ویذ تَکت', vocabulary: [{ word: 'tact', meaning: 'ملاحظه و مهارت در برخورد', essential504: true }] },
      { id: 'misunderstanding-conceal', en: 'I do not want to conceal my feelings.', fa: 'نمی‌خواهم احساساتم را پنهان کنم.', pronunciation: 'آی دو نات وانت تو کِنسیل مای فیلینگز', pattern: 'want to + verb', vocabulary: [{ word: 'conceal', meaning: 'پنهان کردن', essential504: true }] },
      { id: 'misunderstanding-resent', en: 'I do not want to resent you.', fa: 'نمی‌خواهم از تو دلخور بمانم.', pronunciation: 'آی دو نات وانت تو ریزِنت یو', vocabulary: [{ word: 'resent', meaning: 'دلخور یا رنجیده بودن', essential504: true }] },
      { id: 'misunderstanding-listen', en: 'Please listen before you answer.', fa: 'لطفاً پیش از پاسخ‌دادن گوش کن.', pronunciation: 'پلیز لیسِن بیفور یو اَنسِر', vocabulary: [{ word: 'listen', meaning: 'گوش دادن' }] },
      { id: 'misunderstanding-clear', en: 'I am glad we cleared this up.', fa: 'خوشحالم که این سوءتفاهم را برطرف کردیم.', pronunciation: 'آی اَم گِلَد وی کلیرْد ذیس آپ', vocabulary: [{ word: 'clear up', meaning: 'برطرف‌کردن سوءتفاهم' }] },
    ],
    dialogue: [
      { speaker: 'learner', text: 'I do not want to conceal my feelings.', fa: 'نمی‌خواهم احساساتم را پنهان کنم.' },
      { speaker: 'partner', text: 'I understand. Let us discuss this with tact.', fa: 'متوجه‌ام. بیایید با ملاحظه صحبت کنیم.' },
      { speaker: 'learner', text: 'Thank you. I do not want to resent you.', fa: 'ممنون. نمی‌خواهم از تو دلخور بمانم.' },
    ],
  },
  {
    id: 'everyday-talking-about-weather',
    levelId: 2,
    order: 9,
    title: 'صحبت درباره هوا',
    subtitle: 'توصیف شرایط هوا و برنامه‌ریزی',
    situation: 'پیش از بیرون‌رفتن، وضعیت هوا را با دوستتان بررسی می‌کنید و درباره برنامه روز تصمیم می‌گیرید.',
    durationMinutes: 11,
    sentences: [
      { id: 'weather-frigid', en: 'The air is frigid this morning.', fa: 'هوای امروز صبح بسیار سرد است.', pronunciation: 'ذی اِر ایز فریجید ذیس مورنینگ', vocabulary: [{ word: 'frigid', meaning: 'بسیار سرد', essential504: true }] },
      { id: 'weather-humid', en: 'It will be hot and humid this afternoon.', fa: 'امروز بعدازظهر هوا گرم و مرطوب خواهد بود.', pronunciation: 'ایت ویل بی هات اَند هیومید ذیس اَفتِرنون', vocabulary: [{ word: 'humid', meaning: 'مرطوب و شرجی', essential504: true }] },
      { id: 'weather-dense', en: 'Dense fog is covering the road.', fa: 'مه غلیظ جاده را پوشانده است.', pronunciation: 'دِنس فاگ ایز کاوِرینگ ذِ رود', vocabulary: [{ word: 'dense', meaning: 'غلیظ / متراکم', essential504: true }] },
      { id: 'weather-predict', en: 'They predict rain later today.', fa: 'آن‌ها برای ساعات بعدی امروز باران پیش‌بینی می‌کنند.', pronunciation: 'ذِی پریدیکت رِین لِیتِر تودی', vocabulary: [{ word: 'predict', meaning: 'پیش‌بینی کردن', essential504: true }] },
      { id: 'weather-jacket', en: 'Take a warm jacket with you.', fa: 'یک کت گرم همراهت ببر.', pronunciation: 'تِیک اَ وُرم جَکِت ویذ یو', vocabulary: [{ word: 'jacket', meaning: 'کت / کاپشن' }] },
      { id: 'weather-delay', en: 'We may need to leave later.', fa: 'شاید لازم باشد دیرتر حرکت کنیم.', pronunciation: 'وی مِی نید تو لیو لِیتِر', vocabulary: [{ word: 'later', meaning: 'دیرتر' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Can we drive now?', fa: 'می‌توانیم الان رانندگی کنیم؟' },
      { speaker: 'learner', text: 'Dense fog is covering the road.', fa: 'مه غلیظ جاده را پوشانده است.' },
      { speaker: 'partner', text: 'What do they predict?', fa: 'چه چیزی پیش‌بینی کرده‌اند؟' },
      { speaker: 'learner', text: 'They predict rain later today.', fa: 'برای ساعات بعدی امروز باران پیش‌بینی کرده‌اند.' },
    ],
  },
  {
    id: 'everyday-handling-an-emergency',
    levelId: 2,
    order: 10,
    title: 'مدیریت یک وضعیت اضطراری',
    subtitle: 'توضیح خطر و درخواست کمک',
    situation: 'در یک سفر سرد با اتفاقی غیرمنتظره روبه‌رو شده‌اید و باید وضعیت را سریع و روشن توضیح دهید.',
    durationMinutes: 12,
    sentences: [
      { id: 'emergency-peril', en: 'The hikers are in serious peril.', fa: 'کوهنوردان در خطر جدی هستند.', pronunciation: 'ذِ هایکِرز آر این سیریِس پِرِل', vocabulary: [{ word: 'peril', meaning: 'خطر جدی', essential504: true }] },
      { id: 'emergency-numb', en: 'My fingers are numb from the cold.', fa: 'انگشتانم از سرما بی‌حس شده‌اند.', pronunciation: 'مای فینگِرز آر نام فرام ذِ کُلد', vocabulary: [{ word: 'numb', meaning: 'بی‌حس', essential504: true }] },
      { id: 'emergency-survive', en: 'We can survive if we stay together.', fa: 'اگر کنار هم بمانیم می‌توانیم زنده بمانیم.', pronunciation: 'وی کَن سِروایو ایف وی اِستِی توگِذِر', vocabulary: [{ word: 'survive', meaning: 'زنده ماندن / جان سالم بردن', essential504: true }] },
      { id: 'emergency-unforeseen', en: 'An unforeseen storm blocked the road.', fa: 'یک طوفان پیش‌بینی‌نشده جاده را مسدود کرد.', pronunciation: 'اَن آنفورسین اِستورم بلاکت ذِ رود', vocabulary: [{ word: 'unforeseen', meaning: 'پیش‌بینی‌نشده', essential504: true }] },
      { id: 'emergency-location', en: 'I will send our exact location.', fa: 'موقعیت دقیقمان را ارسال می‌کنم.', pronunciation: 'آی ویل سِند آور اِگزَکت لوکِیشِن', vocabulary: [{ word: 'location', meaning: 'موقعیت مکانی' }] },
      { id: 'emergency-help', en: 'Please send help as soon as possible.', fa: 'لطفاً هرچه سریع‌تر کمک بفرستید.', pronunciation: 'پلیز سِند هِلپ اَز سون اَز پاسِبِل', vocabulary: [{ word: 'as soon as possible', meaning: 'هرچه سریع‌تر' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What happened?', fa: 'چه اتفاقی افتاد؟' },
      { speaker: 'learner', text: 'An unforeseen storm blocked the road.', fa: 'یک طوفان پیش‌بینی‌نشده جاده را بست.' },
      { speaker: 'partner', text: 'Are you safe?', fa: 'آیا در امان هستید؟' },
      { speaker: 'learner', text: 'We are in peril, but we can survive if help comes soon.', fa: 'در خطر هستیم، اما اگر کمک زود برسد می‌توانیم زنده بمانیم.' },
    ],
  },
  {
    id: 'communication-university-discussion',
    levelId: 3,
    order: 11,
    title: 'گفت‌وگو در دانشگاه',
    subtitle: 'شرکت در یک بحث گروهی',
    situation: 'در دانشگاه درباره یک موضوع مهم جلسه دارید و می‌خواهید نظر گروه را بشنوید و دیدگاه خود را بیان کنید.',
    durationMinutes: 13,
    sentences: [
      { id: 'university-campus', en: 'The meeting will take place on campus.', fa: 'جلسه در محوطه دانشگاه برگزار می‌شود.', pronunciation: 'ذِ میتینگ ویل تِیک پِلِیس آن کَمپِس', vocabulary: [{ word: 'campus', meaning: 'محوطه دانشگاه', essential504: true }] },
      { id: 'university-majority', en: 'The majority of students support the idea.', fa: 'اکثریت دانشجویان از این ایده حمایت می‌کنند.', pronunciation: 'ذِ مَجورِتی آو اِستیودِنتس ساپورت ذی آیدیا', vocabulary: [{ word: 'majority', meaning: 'اکثریت', essential504: true }] },
      { id: 'university-assemble', en: 'We will assemble in the main hall.', fa: 'در سالن اصلی گرد هم می‌آییم.', pronunciation: 'وی ویل اَسِمبِل این ذِ مِین هال', vocabulary: [{ word: 'assemble', meaning: 'گرد هم آمدن', essential504: true }] },
      { id: 'university-debate', en: 'We should debate both sides of the issue.', fa: 'باید درباره هر دو طرف موضوع بحث کنیم.', pronunciation: 'وی شود دِبِیت بوث سایدز آو ذی ایشو', vocabulary: [{ word: 'debate', meaning: 'بحث و مناظره کردن', essential504: true }] },
      { id: 'university-opinion', en: 'I would like to share my opinion.', fa: 'می‌خواهم نظرم را بیان کنم.', pronunciation: 'آی وود لایک تو شِر مای اَپینیِن', vocabulary: [{ word: 'opinion', meaning: 'نظر' }] },
      { id: 'university-respect', en: 'Let us listen to each other respectfully.', fa: 'بیایید با احترام به یکدیگر گوش کنیم.', pronunciation: 'لِت آس لیسِن تو ایچ آذِر ریسپِکتفولی', vocabulary: [{ word: 'respectfully', meaning: 'با احترام' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Does everyone support this idea?', fa: 'آیا همه از این ایده حمایت می‌کنند؟' },
      { speaker: 'learner', text: 'The majority support it, but we should debate both sides.', fa: 'اکثریت حمایت می‌کنند، اما باید هر دو طرف را بررسی کنیم.' },
      { speaker: 'partner', text: 'Good. We will assemble on campus tomorrow.', fa: 'خوب است. فردا در دانشگاه جمع می‌شویم.' },
    ],
  },
  {
    id: 'communication-working-with-a-client',
    levelId: 3,
    order: 12,
    title: 'صحبت با مشتری',
    subtitle: 'بررسی دقیق یک درخواست کاری',
    situation: 'در محل کار با یک مشتری جلسه دارید و باید نیاز او را دقیق بفهمید و راه‌حل مناسبی پیشنهاد کنید.',
    durationMinutes: 13,
    sentences: [
      { id: 'client-approach', en: 'We need a different approach to this problem.', fa: 'برای این مشکل به رویکرد متفاوتی نیاز داریم.', pronunciation: 'وی نید اَ دیفِرِنت اَپروچ تو ذیس پرابلِم', vocabulary: [{ word: 'approach', meaning: 'رویکرد / روش برخورد', essential504: true }] },
      { id: 'client-employee', en: 'One of our employees will assist you.', fa: 'یکی از کارکنان ما به شما کمک خواهد کرد.', pronunciation: 'وان آو آور اِمپلوییز ویل اَسیست یو', vocabulary: [{ word: 'employee', meaning: 'کارمند', essential504: true }] },
      { id: 'client-client', en: 'The client needs a simple solution.', fa: 'مشتری به یک راه‌حل ساده نیاز دارد.', pronunciation: 'ذِ کلایِنت نیدز اَ سیمپِل سِلوشِن', vocabulary: [{ word: 'client', meaning: 'مشتری / موکل', essential504: true }] },
      { id: 'client-thorough', en: 'We will conduct a thorough review.', fa: 'یک بررسی کامل و دقیق انجام خواهیم داد.', pronunciation: 'وی ویل کِنداکت اَ ثِرو ریویو', vocabulary: [{ word: 'thorough', meaning: 'کامل و دقیق', essential504: true }] },
      { id: 'client-deadline', en: 'When is the final deadline?', fa: 'مهلت نهایی چه زمانی است؟', pronunciation: 'وِن ایز ذِ فاینِل دِدلاین؟', vocabulary: [{ word: 'deadline', meaning: 'مهلت نهایی' }] },
      { id: 'client-update', en: 'I will send you an update tomorrow.', fa: 'فردا گزارش تازه‌ای برایتان می‌فرستم.', pronunciation: 'آی ویل سِند یو اَن آپدِیت تومارو', vocabulary: [{ word: 'update', meaning: 'گزارش تازه / به‌روزرسانی' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What does the client need?', fa: 'مشتری چه چیزی نیاز دارد؟' },
      { speaker: 'learner', text: 'The client needs a simple solution.', fa: 'مشتری یک راه‌حل ساده می‌خواهد.' },
      { speaker: 'partner', text: 'What is your approach?', fa: 'رویکرد شما چیست؟' },
      { speaker: 'learner', text: 'First, we will conduct a thorough review.', fa: 'ابتدا یک بررسی کامل و دقیق انجام می‌دهیم.' },
    ],
  },
  {
    id: 'communication-health-checkup',
    levelId: 3,
    order: 13,
    title: 'معاینه پزشکی',
    subtitle: 'توضیح علائم و دنبال‌کردن توصیه‌ها',
    situation: 'برای یک معاینه به پزشک مراجعه کرده‌اید و درباره علائم، پیشگیری و مراقبت از سلامتی صحبت می‌کنید.',
    durationMinutes: 13,
    sentences: [
      { id: 'health-detect', en: 'This test can detect the problem early.', fa: 'این آزمایش می‌تواند مشکل را زود تشخیص دهد.', pronunciation: 'ذیس تِست کَن دیتِکت ذِ پرابلِم اِرلی', vocabulary: [{ word: 'detect', meaning: 'تشخیص دادن / کشف کردن', essential504: true }] },
      { id: 'health-neglect', en: 'Do not neglect these symptoms.', fa: 'این علائم را نادیده نگیرید.', pronunciation: 'دو نات نیگِلِکت ذیز سیمپتِمز', vocabulary: [{ word: 'neglect', meaning: 'نادیده گرفتن / غفلت کردن', essential504: true }] },
      { id: 'health-preserve', en: 'Regular exercise helps preserve your health.', fa: 'ورزش منظم به حفظ سلامتی شما کمک می‌کند.', pronunciation: 'رِگیولِر اِکسِرسایز هِلپس پریزِرو یور هِلث', vocabulary: [{ word: 'preserve', meaning: 'حفظ کردن', essential504: true }] },
      { id: 'health-obvious', en: 'There is no obvious sign of infection.', fa: 'نشانه آشکاری از عفونت وجود ندارد.', pronunciation: 'ذِر ایز نو آبویِس ساین آو اینفِکشِن', vocabulary: [{ word: 'obvious', meaning: 'آشکار / واضح', essential504: true }] },
      { id: 'health-pain', en: 'The pain started two days ago.', fa: 'درد دو روز پیش شروع شد.', pronunciation: 'ذِ پِین اِستارتِد تو دِیز اَگو', vocabulary: [{ word: 'pain', meaning: 'درد' }] },
      { id: 'health-follow', en: 'I will follow your advice.', fa: 'توصیه شما را دنبال می‌کنم.', pronunciation: 'آی ویل فالو یور اَدوایس', vocabulary: [{ word: 'advice', meaning: 'توصیه' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'When did the pain start?', fa: 'درد چه زمانی شروع شد؟' },
      { speaker: 'learner', text: 'The pain started two days ago.', fa: 'درد دو روز پیش شروع شد.' },
      { speaker: 'partner', text: 'Do not neglect these symptoms. This test can detect the problem early.', fa: 'این علائم را نادیده نگیرید. این آزمایش می‌تواند مشکل را زود تشخیص دهد.' },
    ],
  },
  {
    id: 'communication-community-change',
    levelId: 3,
    order: 14,
    title: 'تغییر در جامعه',
    subtitle: 'صحبت درباره سنت و پیشرفت',
    situation: 'در یک گفت‌وگوی اجتماعی درباره زندگی خارج از شهر و راه‌های بهترشدن شرایط مردم نظر می‌دهید.',
    durationMinutes: 13,
    sentences: [
      { id: 'community-tradition', en: 'This tradition is important to our community.', fa: 'این سنت برای جامعه ما مهم است.', pronunciation: 'ذیس تِرَدیشِن ایز ایمپورتِنت تو آور کِمیونِتی', vocabulary: [{ word: 'tradition', meaning: 'سنت', essential504: true }] },
      { id: 'community-rural', en: 'Many rural areas need better services.', fa: 'بسیاری از مناطق روستایی به خدمات بهتری نیاز دارند.', pronunciation: 'مِنی رورِل اِریاز نید بِتِر سِرویسِز', vocabulary: [{ word: 'rural', meaning: 'روستایی', essential504: true }] },
      { id: 'community-explore', en: 'We should explore several solutions.', fa: 'باید چند راه‌حل را بررسی کنیم.', pronunciation: 'وی شود اِکسپلور سِوِرِل سِلوشِنز', vocabulary: [{ word: 'explore', meaning: 'بررسی کردن / کاوش کردن', essential504: true }] },
      { id: 'community-reform', en: 'The city plans to reform the system.', fa: 'شهر قصد دارد سیستم را اصلاح کند.', pronunciation: 'ذِ سیتی پِلَنز تو ریفورم ذِ سیستم', vocabulary: [{ word: 'reform', meaning: 'اصلاح کردن', essential504: true }] },
      { id: 'community-protect', en: 'We can improve life and protect our culture.', fa: 'می‌توانیم زندگی را بهتر کنیم و از فرهنگمان محافظت کنیم.', pronunciation: 'وی کَن ایمپروو لایف اَند پروتِکت آور کالچِر', vocabulary: [{ word: 'culture', meaning: 'فرهنگ' }] },
      { id: 'community-voice', en: 'Local people should have a voice.', fa: 'مردم محلی باید حق اظهار نظر داشته باشند.', pronunciation: 'لوکِل پیپِل شود هَو اَ وُیس', vocabulary: [{ word: 'have a voice', meaning: 'حق اظهار نظر داشتن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Should everything change?', fa: 'آیا همه‌چیز باید تغییر کند؟' },
      { speaker: 'learner', text: 'No. This tradition is important to our community.', fa: 'نه. این سنت برای جامعه ما مهم است.' },
      { speaker: 'partner', text: 'Then what should we do?', fa: 'پس باید چه کار کنیم؟' },
      { speaker: 'learner', text: 'We should explore solutions that improve rural services and protect our culture.', fa: 'باید راه‌هایی برای بهبود خدمات روستایی و حفظ فرهنگمان بررسی کنیم.' },
    ],
  },
  {
    id: 'communication-changing-plans',
    levelId: 3,
    order: 15,
    title: 'تغییر یک برنامه',
    subtitle: 'درخواست موافقت و توضیح دلیل',
    situation: 'به‌دلیل یک مشکل کاری باید برنامه گروه را تغییر دهید و موافقت دیگران را با احترام بگیرید.',
    durationMinutes: 12,
    sentences: [
      { id: 'change-postpone', en: 'We need to postpone the meeting.', fa: 'باید جلسه را به تعویق بیندازیم.', pronunciation: 'وی نید تو پوستپون ذِ میتینگ', vocabulary: [{ word: 'postpone', meaning: 'به تعویق انداختن', essential504: true }] },
      { id: 'change-consent', en: 'We cannot proceed without your consent.', fa: 'بدون موافقت شما نمی‌توانیم ادامه دهیم.', pronunciation: 'وی کَنات پروسید ویداوت یور کِنسِنت', vocabulary: [{ word: 'consent', meaning: 'رضایت / موافقت', essential504: true }] },
      { id: 'change-reluctant', en: 'I am reluctant to change the date again.', fa: 'تمایلی ندارم دوباره تاریخ را تغییر دهم.', pronunciation: 'آی اَم ریلَکتِنت تو چِینج ذِ دِیت اَگِن', pattern: 'be reluctant to + verb', vocabulary: [{ word: 'reluctant', meaning: 'بی‌میل / مردد', essential504: true }] },
      { id: 'change-valid', en: 'That is a valid reason to wait.', fa: 'این دلیل معتبری برای صبرکردن است.', pronunciation: 'ذَت ایز اَ وَلید ریزِن تو وِیت', vocabulary: [{ word: 'valid', meaning: 'معتبر / قابل‌قبول', essential504: true }] },
      { id: 'change-available', en: 'Is everyone available on Friday?', fa: 'آیا همه جمعه وقت دارند؟', pronunciation: 'ایز اِوری‌وان اَوِیلِبِل آن فرایدِی؟', vocabulary: [{ word: 'available', meaning: 'در دسترس / آزاد' }] },
      { id: 'change-confirm', en: 'Please confirm the new time today.', fa: 'لطفاً زمان جدید را امروز تأیید کنید.', pronunciation: 'پلیز کِنفِرم ذِ نیو تایم تودی', vocabulary: [{ word: 'confirm', meaning: 'تأیید کردن' }] },
    ],
    dialogue: [
      { speaker: 'learner', text: 'We need to postpone the meeting.', fa: 'باید جلسه را به تعویق بیندازیم.' },
      { speaker: 'partner', text: 'I am reluctant to change the date again.', fa: 'تمایلی ندارم دوباره تاریخ را تغییر دهم.' },
      { speaker: 'learner', text: 'I understand, but we have a valid reason. We need your consent.', fa: 'متوجه‌ام، اما دلیل معتبری داریم و به موافقت شما نیاز داریم.' },
    ],
  },
];
