import type { SentenceLesson } from './courseContent';

/** Eighth original content pack: 32 verified words from the canonical 504 list. */
export const ADVANCED_SENTENCE_LESSONS_7: SentenceLesson[] = [
  {
    id: 'advanced-giving-court-testimony', levelId: 4, order: 64,
    title: 'ارائه شهادت در دادگاه', subtitle: 'بیان حقیقت و بررسی مدرک',
    situation: 'در یک پرونده مالی، شاهد باید با دقت درباره مدارک و اتفاقات صحبت کند.', durationMinutes: 14,
    sentences: [
      { id: 'court-oath', en: 'The witness took an oath to tell the truth.', fa: 'شاهد سوگند خورد حقیقت را بگوید.', pronunciation: 'ذِ ویتنِس توک اَن اوث تو تِل ذِ تروث', vocabulary: [{ word: 'oath', meaning: 'سوگند', essential504: true }] },
      { id: 'court-corpse', en: 'The report confirmed that no corpse was found at the scene.', fa: 'گزارش تأیید کرد که هیچ جسدی در محل پیدا نشد.', pronunciation: 'ذِ ریپورت کِنفِرمد ذَت نو کورپس واز فَوند اَت ذِ سین', vocabulary: [{ word: 'corpse', meaning: 'جسد', essential504: true }] },
      { id: 'court-undeniable', en: 'The bank record provides undeniable evidence.', fa: 'سابقه بانکی مدرکی انکارناپذیر ارائه می‌دهد.', pronunciation: 'ذِ بَنک رِکورد پرووایدز آندِنایِبِل اِویدِنس', vocabulary: [{ word: 'undeniable', meaning: 'انکارناپذیر', essential504: true }] },
      { id: 'court-defraud', en: 'The suspect tried to defraud several customers.', fa: 'مظنون تلاش کرد چند مشتری را فریب مالی دهد.', pronunciation: 'ذِ ساسپِکت تِراید تو دیفْراد سِوِرِل کاستِمِرز', vocabulary: [{ word: 'defraud', meaning: 'کلاهبرداری کردن', essential504: true }] },
      { id: 'court-answer', en: 'Answer only the question you are asked.', fa: 'فقط به سؤالی که از شما پرسیده می‌شود پاسخ دهید.', pronunciation: 'اَنسِر اونلی ذِ کوئسچِن یو آر اَسکت', vocabulary: [{ word: 'witness', meaning: 'شاهد' }] },
      { id: 'court-record', en: 'The judge examined the original records.', fa: 'قاضی مدارک اصلی را بررسی کرد.', pronunciation: 'ذِ جاج اِگْزَمِند ذی اریجِنِل رِکوردز', vocabulary: [{ word: 'record', meaning: 'سابقه / مدرک' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Did the witness take an oath?', fa: 'شاهد سوگند خورد؟' },
      { speaker: 'learner', text: 'Yes, and the bank record gave undeniable evidence of fraud.', fa: 'بله و سابقه بانکی مدرک انکارناپذیری از کلاهبرداری ارائه داد.' },
      { speaker: 'partner', text: 'What was the suspect accused of?', fa: 'مظنون به چه چیزی متهم شد؟' },
      { speaker: 'learner', text: 'Trying to defraud several customers.', fa: 'تلاش برای کلاهبرداری از چند مشتری.' },
    ],
  },
  {
    id: 'advanced-improving-poor-housing', levelId: 4, order: 65,
    title: 'بهبود شرایط مسکن', subtitle: 'شناخت کمبودها و درخواست اقدام',
    situation: 'ساکنان درباره شرایط نامناسب یک مجموعه مسکونی و مسئولیت مدیر ساختمان گفت‌وگو می‌کنند.', durationMinutes: 14,
    sentences: [
      { id: 'housing-inhabit', en: 'More than fifty families inhabit these buildings.', fa: 'بیش از پنجاه خانواده در این ساختمان‌ها زندگی می‌کنند.', pronunciation: 'مور ذَن فیفتی فَمِلیز اِن‌هَبیت ذیز بیلدینگز', vocabulary: [{ word: 'inhabit', meaning: 'ساکن بودن', essential504: true }] },
      { id: 'housing-dismal', en: 'The basement is in dismal condition.', fa: 'زیرزمین در وضعیت بسیار بدی قرار دارد.', pronunciation: 'ذِ بِیس‌مِنت ایز این دیزمِل کِندیشِن', vocabulary: [{ word: 'dismal', meaning: 'بسیار بد و ناامیدکننده', essential504: true }] },
      { id: 'housing-lack', en: 'Several apartments lack proper heating.', fa: 'چند آپارتمان گرمایش مناسب ندارند.', pronunciation: 'سِوِرِل اَپارت‌مِنتس لَک پراپِر هیتینگ', vocabulary: [{ word: 'lack', meaning: 'فاقد بودن / کمبود داشتن', essential504: true }] },
      { id: 'housing-ignore', en: 'The owner cannot ignore these complaints.', fa: 'مالک نمی‌تواند این شکایت‌ها را نادیده بگیرد.', pronunciation: 'ذی اونِر کَنات ایگنور ذیز کِمپلِینتس', vocabulary: [{ word: 'ignore', meaning: 'نادیده گرفتن', essential504: true }] },
      { id: 'housing-inspection', en: 'We requested an official inspection.', fa: 'درخواست بازرسی رسمی کردیم.', pronunciation: 'وی ریکوئِستِد اَن اُفیشِل اینسپِکشِن', vocabulary: [{ word: 'inspection', meaning: 'بازرسی' }] },
      { id: 'housing-deadline', en: 'Repairs must begin before winter.', fa: 'تعمیرات باید پیش از زمستان شروع شوند.', pronunciation: 'ریپِرز ماست بِگین بیفور وینتِر', vocabulary: [{ word: 'repair', meaning: 'تعمیر' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'How many families inhabit these buildings?', fa: 'چند خانواده در این ساختمان‌ها زندگی می‌کنند؟' },
      { speaker: 'learner', text: 'More than fifty, and many apartments lack proper heating.', fa: 'بیش از پنجاه خانواده و بسیاری گرمایش مناسب ندارند.' },
      { speaker: 'partner', text: 'Has the owner responded?', fa: 'مالک پاسخ داده است؟' },
      { speaker: 'learner', text: 'No. The owner continues to ignore the dismal conditions.', fa: 'نه. مالک همچنان شرایط بسیار بد را نادیده می‌گیرد.' },
    ],
  },
  {
    id: 'advanced-designing-a-product-model', levelId: 4, order: 66,
    title: 'طراحی نمونه محصول', subtitle: 'ترکیب مواد و بررسی جزئیات',
    situation: 'تیم طراحی یک نمونه کوچک ساخته و درباره ظاهر، مواد و تعداد قطعات آن صحبت می‌کند.', durationMinutes: 13,
    sentences: [
      { id: 'design-blend', en: 'We need to blend strength with a simple design.', fa: 'باید استحکام را با طراحی ساده ترکیب کنیم.', pronunciation: 'وی نید تو بِلِند اِسترِنگث ویذ اَ سیمپِل دیزاین', vocabulary: [{ word: 'blend', meaning: 'ترکیب کردن', essential504: true }] },
      { id: 'design-visible', en: 'The controls must remain clearly visible.', fa: 'دکمه‌های کنترل باید کاملاً قابل‌مشاهده بمانند.', pronunciation: 'ذِ کِنترولز ماست ریمِین کلیرلی ویزِبِل', vocabulary: [{ word: 'visible', meaning: 'قابل‌مشاهده', essential504: true }] },
      { id: 'design-miniature', en: 'This miniature model shows the final shape.', fa: 'این مدل کوچک شکل نهایی را نشان می‌دهد.', pronunciation: 'ذیس مینیِچِر مادِل شوز ذِ فاینِل شِیپ', vocabulary: [{ word: 'miniature', meaning: 'کوچک و مینیاتوری', essential504: true }] },
      { id: 'design-numerous', en: 'The first version had numerous small parts.', fa: 'نسخه اول قطعات کوچک فراوانی داشت.', pronunciation: 'ذِ فِرست وِرژِن هَد نیومِرِس اِسمال پارتس', vocabulary: [{ word: 'numerous', meaning: 'فراوان / متعدد', essential504: true }] },
      { id: 'design-test', en: 'Let users test the model before production.', fa: 'پیش از تولید اجازه دهید کاربران مدل را آزمایش کنند.', pronunciation: 'لِت یوزِرز تِست ذِ مادِل بیفور پروداکشِن', vocabulary: [{ word: 'production', meaning: 'تولید' }] },
      { id: 'design-feedback', en: 'Their feedback will guide the next version.', fa: 'بازخورد آن‌ها نسخه بعدی را هدایت می‌کند.', pronunciation: 'ذِر فیدبَک ویل گاید ذِ نِکست وِرژِن', vocabulary: [{ word: 'version', meaning: 'نسخه' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why did you build a miniature model?', fa: 'چرا مدل کوچک ساختید؟' },
      { speaker: 'learner', text: 'It makes the final shape visible before production.', fa: 'شکل نهایی را پیش از تولید قابل‌مشاهده می‌کند.' },
      { speaker: 'partner', text: 'What was wrong with the first version?', fa: 'مشکل نسخه اول چه بود؟' },
      { speaker: 'learner', text: 'It had numerous parts, so we need a simpler blend of materials.', fa: 'قطعات زیادی داشت، پس به ترکیب ساده‌تری از مواد نیاز داریم.' },
    ],
  },
  {
    id: 'advanced-planning-wholesale-growth', levelId: 4, order: 67,
    title: 'برنامه رشد عمده‌فروشی', subtitle: 'آزمودن نظریه و ارزیابی توانایی',
    situation: 'یک کسب‌وکار کوچک می‌خواهد وارد فروش عمده شود و پیش از تصمیم نهایی فرضیات خود را بررسی می‌کند.', durationMinutes: 14,
    sentences: [
      { id: 'wholesale-wholesale', en: 'Wholesale prices are lower than retail prices.', fa: 'قیمت‌های عمده‌فروشی از قیمت خرده‌فروشی پایین‌ترند.', pronunciation: 'هول‌سِیل پرایسِز آر لوئِر ذَن ریتِیل پرایسِز', vocabulary: [{ word: 'wholesale', meaning: 'عمده‌فروشی', essential504: true }] },
      { id: 'wholesale-theory', en: 'Our theory is that larger orders will reduce costs.', fa: 'نظریه ما این است که سفارش‌های بزرگ‌تر هزینه را کاهش می‌دهند.', pronunciation: 'آور ثیِری ایز ذَت لارجِر اُردِرز ویل ریدیوس کاستس', vocabulary: [{ word: 'theory', meaning: 'نظریه', essential504: true }] },
      { id: 'wholesale-underestimate', en: 'Do not underestimate the cost of storage.', fa: 'هزینه انبارداری را دست‌کم نگیرید.', pronunciation: 'دو نات آندِر اِستِمِیت ذِ کاست آو اِستورِج', vocabulary: [{ word: 'underestimate', meaning: 'دست‌کم گرفتن', essential504: true }] },
      { id: 'wholesale-excel', en: 'We excel at personal customer service.', fa: 'ما در خدمات شخصی به مشتری بسیار خوب عمل می‌کنیم.', pronunciation: 'وی اِکسِل اَت پِرسِنِل کاستِمِر سِرویس', vocabulary: [{ word: 'excel', meaning: 'برتری داشتن / بسیار خوب بودن', essential504: true }] },
      { id: 'wholesale-pilot', en: 'Start with a small trial order.', fa: 'با یک سفارش آزمایشی کوچک شروع کنید.', pronunciation: 'اِستارت ویذ اَ اِسمال تِرایِل اُردِر', vocabulary: [{ word: 'trial order', meaning: 'سفارش آزمایشی' }] },
      { id: 'wholesale-review', en: 'Review the real costs after one month.', fa: 'پس از یک ماه هزینه‌های واقعی را بررسی کنید.', pronunciation: 'ریویو ذِ ریل کاستس اَفتِر وان مانث', vocabulary: [{ word: 'storage', meaning: 'انبارداری' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why consider wholesale sales?', fa: 'چرا فروش عمده را بررسی کنیم؟' },
      { speaker: 'learner', text: 'Our theory is that larger orders will lower costs.', fa: 'نظریه ما این است که سفارش‌های بزرگ‌تر هزینه را کم می‌کنند.' },
      { speaker: 'partner', text: 'What risk do you see?', fa: 'چه خطری می‌بینید؟' },
      { speaker: 'learner', text: 'We must not underestimate storage costs.', fa: 'نباید هزینه انبارداری را دست‌کم بگیریم.' },
    ],
  },
  {
    id: 'advanced-protecting-people-in-public', levelId: 4, order: 68,
    title: 'محافظت از مردم در فضای عمومی', subtitle: 'محکوم‌کردن آزار و کنترل خشم',
    situation: 'شورای محلی درباره مزاحمت خیابانی و راه‌های ایجاد فضای عمومی امن‌تر گفت‌وگو می‌کند.', durationMinutes: 14,
    sentences: [
      { id: 'safety-denounce', en: 'Community leaders must denounce harassment.', fa: 'رهبران جامعه باید آزار را محکوم کنند.', pronunciation: 'کِمیونِتی لیدِرز ماست دِناونس هَرَس‌مِنت', vocabulary: [{ word: 'denounce', meaning: 'محکوم کردن', essential504: true }] },
      { id: 'safety-molest', en: 'No one has the right to molest people in public.', fa: 'هیچ‌کس حق ندارد در فضای عمومی برای مردم مزاحمت ایجاد کند.', pronunciation: 'نو وان هَز ذِ رایت تو مِلِست پیپِل این پابلیک', vocabulary: [{ word: 'molest', meaning: 'مزاحمت و آزار ایجاد کردن', essential504: true }] },
      { id: 'safety-rage', en: 'Uncontrolled rage can put others in danger.', fa: 'خشم کنترل‌نشده می‌تواند دیگران را در خطر قرار دهد.', pronunciation: 'آنکِنترولْد رِیج کَن پوت آذِرز این دِینجِر', vocabulary: [{ word: 'rage', meaning: 'خشم شدید', essential504: true }] },
      { id: 'safety-menace', en: 'Repeated threats can become a serious menace.', fa: 'تهدیدهای تکراری می‌توانند به خطری جدی تبدیل شوند.', pronunciation: 'ریپیتِد ثرِتس کَن بِکام اَ سیریِس مِنیس', vocabulary: [{ word: 'menace', meaning: 'خطر / تهدید جدی', essential504: true }] },
      { id: 'safety-report', en: 'Provide a safe and private way to report abuse.', fa: 'راهی امن و خصوصی برای گزارش آزار فراهم کنید.', pronunciation: 'پروواید اَ سِیف اَند پرایوِت وِی تو ریپورت اَبیوس', vocabulary: [{ word: 'harassment', meaning: 'مزاحمت و آزار' }] },
      { id: 'safety-support', en: 'Trained staff should support the victim.', fa: 'کارکنان آموزش‌دیده باید از قربانی حمایت کنند.', pronunciation: 'تِرِیند اِستَف شود ساپورت ذِ ویکتیم', vocabulary: [{ word: 'victim', meaning: 'قربانی' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why must leaders denounce this behavior?', fa: 'چرا رهبران باید این رفتار را محکوم کنند؟' },
      { speaker: 'learner', text: 'Because no one should molest people or become a public menace.', fa: 'چون هیچ‌کس نباید مردم را آزار دهد یا به خطر عمومی تبدیل شود.' },
      { speaker: 'partner', text: 'What can uncontrolled rage cause?', fa: 'خشم کنترل‌نشده چه پیامدی دارد؟' },
      { speaker: 'learner', text: 'It can put other people in serious danger.', fa: 'می‌تواند دیگران را در خطر جدی قرار دهد.' },
    ],
  },
  {
    id: 'advanced-leading-a-difficult-expedition', levelId: 4, order: 69,
    title: 'هدایت سفر دشوار', subtitle: 'غلبه بر ترس و رسیدن به هدف',
    situation: 'یک گروه در مسیر صعود با ترس و خستگی روبه‌رو شده و رهبر باید تصمیمی شجاعانه بگیرد.', durationMinutes: 14,
    sentences: [
      { id: 'expedition-mount', en: 'We will mount the final slope at sunrise.', fa: 'هنگام طلوع از شیب نهایی بالا می‌رویم.', pronunciation: 'وی ویل ماونت ذِ فاینِل اِسلوپ اَت سان‌رایز', vocabulary: [{ word: 'mount', meaning: 'بالارفتن / صعودکردن', essential504: true }] },
      { id: 'expedition-dread', en: 'Some climbers dread the narrow ridge.', fa: 'بعضی کوهنوردان از یال باریک وحشت دارند.', pronunciation: 'سام کِلایمِرز دِرِد ذِ نَرو ریج', vocabulary: [{ word: 'dread', meaning: 'وحشت داشتن', essential504: true }] },
      { id: 'expedition-gallant', en: 'A gallant guide returned to help the injured climber.', fa: 'راهنمایی شجاع برای کمک به کوهنورد مجروح برگشت.', pronunciation: 'اَ گَلِنت گاید ریتِرند تو هِلپ ذی اینجِرد کِلایمِر', vocabulary: [{ word: 'gallant', meaning: 'شجاع و جوانمرد', essential504: true }] },
      { id: 'expedition-victorious', en: 'The team felt victorious when everyone returned safely.', fa: 'وقتی همه سالم برگشتند تیم احساس پیروزی کرد.', pronunciation: 'ذِ تیم فِلت ویکتوریِس وِن اِوری‌وان ریتِرند سِیفلی', vocabulary: [{ word: 'victorious', meaning: 'پیروز', essential504: true }] },
      { id: 'expedition-weather', en: 'We will turn back if the weather changes.', fa: 'اگر هوا تغییر کند برمی‌گردیم.', pronunciation: 'وی ویل تِرن بَک ایف ذِ وِذِر چِینجِز', vocabulary: [{ word: 'turn back', meaning: 'برگشتن' }] },
      { id: 'expedition-team', en: 'No summit is worth a person’s life.', fa: 'هیچ قله‌ای ارزش جان یک انسان را ندارد.', pronunciation: 'نو سامیت ایز وِرث اَ پِرسِنز لایف', vocabulary: [{ word: 'summit', meaning: 'قله' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Some climbers dread the final ridge.', fa: 'بعضی کوهنوردان از یال نهایی می‌ترسند.' },
      { speaker: 'learner', text: 'We will mount it only if the weather remains safe.', fa: 'فقط اگر هوا امن بماند از آن بالا می‌رویم.' },
      { speaker: 'partner', text: 'Why did the guide go back?', fa: 'چرا راهنما برگشت؟' },
      { speaker: 'learner', text: 'It was a gallant decision to help an injured climber.', fa: 'تصمیمی شجاعانه برای کمک به کوهنورد مجروح بود.' },
    ],
  },
  {
    id: 'advanced-examining-a-scientific-sample', levelId: 4, order: 70,
    title: 'بررسی نمونه علمی', subtitle: 'مشاهده دقیق و آزمایش ماده',
    situation: 'در آزمایشگاه با میکروسکوپ نمونه‌ای را بررسی و اثر یک ماده را روی سطح آن آزمایش می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'sample-microscope', en: 'Place the sample under the microscope.', fa: 'نمونه را زیر میکروسکوپ قرار دهید.', pronunciation: 'پِلِیس ذِ سَمپِل آندِر ذِ مایکروسکوپ', vocabulary: [{ word: 'microscope', meaning: 'میکروسکوپ', essential504: true }] },
      { id: 'sample-penetrate', en: 'The liquid can penetrate the outer layer.', fa: 'مایع می‌تواند به لایه بیرونی نفوذ کند.', pronunciation: 'ذِ لیکوئید کَن پِنِترِیت ذی آوتِر لِیِر', vocabulary: [{ word: 'penetrate', meaning: 'نفوذ کردن', essential504: true }] },
      { id: 'sample-pierce', en: 'Do not pierce the sample with the needle yet.', fa: 'هنوز نمونه را با سوزن سوراخ نکنید.', pronunciation: 'دو نات پیرس ذِ سَمپِل ویذ ذِ نیدِل یِت', vocabulary: [{ word: 'pierce', meaning: 'سوراخ کردن', essential504: true }] },
      { id: 'sample-observant', en: 'An observant researcher noticed a tiny change.', fa: 'پژوهشگری دقیق یک تغییر کوچک را متوجه شد.', pronunciation: 'اَن آبزِروِنت ریسِرچِر نوتیست اَ تاینِی چِینج', vocabulary: [{ word: 'observant', meaning: 'دقیق و تیزبین', essential504: true }] },
      { id: 'sample-note', en: 'Write down the color and shape.', fa: 'رنگ و شکل را یادداشت کنید.', pronunciation: 'رایت داون ذِ کالِر اَند شِیپ', vocabulary: [{ word: 'write down', meaning: 'یادداشت کردن' }] },
      { id: 'sample-repeat', en: 'Repeat the test before drawing a conclusion.', fa: 'پیش از نتیجه‌گیری آزمایش را تکرار کنید.', pronunciation: 'ریپیت ذِ تِست بیفور دِرائینگ اَ کِنکلوژِن', vocabulary: [{ word: 'sample', meaning: 'نمونه' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What did you see under the microscope?', fa: 'زیر میکروسکوپ چه دیدید؟' },
      { speaker: 'learner', text: 'An observant researcher noticed that the liquid penetrated the outer layer.', fa: 'پژوهشگر دقیق دید که مایع به لایه بیرونی نفوذ کرده است.' },
      { speaker: 'partner', text: 'Should we pierce the sample now?', fa: 'حالا نمونه را سوراخ کنیم؟' },
      { speaker: 'learner', text: 'Not yet. First, record its color and shape.', fa: 'هنوز نه. ابتدا رنگ و شکلش را ثبت کنیم.' },
    ],
  },
  {
    id: 'advanced-reflecting-on-life-changes', levelId: 4, order: 71,
    title: 'مرور تغییرات زندگی', subtitle: 'مقایسه گذشته و چشم‌انداز آینده',
    situation: 'پس از سال‌ها با یک دوست قدیمی ملاقات می‌کنید و درباره تنهایی، تغییرات اخیر و هدف‌های آینده صحبت می‌کنید.', durationMinutes: 13,
    sentences: [
      { id: 'reflection-solitary', en: 'I spent a solitary year working from home.', fa: 'یک سال را در تنهایی و با کار از خانه گذراندم.', pronunciation: 'آی اِسپِنت اَ سالیتِری ییر وِرکینگ فرام هوم', vocabulary: [{ word: 'solitary', meaning: 'تنها / منزوی', essential504: true }] },
      { id: 'reflection-vision', en: 'My vision for the future has changed.', fa: 'چشم‌انداز من برای آینده تغییر کرده است.', pronunciation: 'مای ویژِن فُر ذِ فیوچِر هَز چِینجد', vocabulary: [{ word: 'vision', meaning: 'چشم‌انداز', essential504: true }] },
      { id: 'reflection-recent', en: 'A recent experience changed my priorities.', fa: 'یک تجربه اخیر اولویت‌هایم را تغییر داد.', pronunciation: 'اَ ریسِنت اِکسپیریِنس چِینجد مای پرایورِتیز', vocabulary: [{ word: 'recent', meaning: 'اخیر', essential504: true }] },
      { id: 'reflection-decade', en: 'We have known each other for a decade.', fa: 'ما ده سال است یکدیگر را می‌شناسیم.', pronunciation: 'وی هَو نون ایچ آذِر فُر اَ دِکِید', vocabulary: [{ word: 'decade', meaning: 'دهه / ده سال', essential504: true }] },
      { id: 'reflection-balance', en: 'I want a better balance between work and family.', fa: 'تعادل بهتری میان کار و خانواده می‌خواهم.', pronunciation: 'آی وانت اَ بِتِر بَلِنس بِتوین وِرک اَند فَمِلی', vocabulary: [{ word: 'balance', meaning: 'تعادل' }] },
      { id: 'reflection-plan', en: 'My next goal is to learn a new skill.', fa: 'هدف بعدی من یادگیری یک مهارت جدید است.', pronunciation: 'مای نِکست گول ایز تو لِرن اَ نیو اِسکیل', vocabulary: [{ word: 'next goal', meaning: 'هدف بعدی' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'How long have we known each other?', fa: 'چند وقت است همدیگر را می‌شناسیم؟' },
      { speaker: 'learner', text: 'For a decade. A lot has changed recently.', fa: 'ده سال. اخیراً چیزهای زیادی تغییر کرده است.' },
      { speaker: 'partner', text: 'What is your vision for the future?', fa: 'چشم‌اندازت برای آینده چیست؟' },
      { speaker: 'learner', text: 'I want less solitary work and more time with family.', fa: 'کار تنهایی کمتر و زمان بیشتری با خانواده می‌خواهم.' },
    ],
  },
];
