import type { SentenceLesson } from './courseContent';

/** Sixth original content pack: 32 more essential words in contextual lessons. */
export const ADVANCED_SENTENCE_LESSONS_5: SentenceLesson[] = [
  {
    id: 'advanced-visiting-a-modern-museum', levelId: 4, order: 48,
    title: 'بازدید از موزه مدرن', subtitle: 'صحبت درباره هنر و طراحی ساختمان',
    situation: 'در یک موزه مدرن درباره نمایشگاه، طراحی بنا و قوانین بازدید صحبت می‌کنید.', durationMinutes: 13,
    sentences: [
      { id: 'museum-exhibit', en: 'The museum will exhibit local artwork this month.', fa: 'موزه این ماه آثار هنری محلی را نمایش می‌دهد.', pronunciation: 'ذِ میوزیِم ویل اِگزیبیت لوکِل آرت‌وِرک ذیس مانث', vocabulary: [{ word: 'exhibit', meaning: 'به نمایش گذاشتن', essential504: true }] },
      { id: 'museum-forbid', en: 'The rules forbid touching the paintings.', fa: 'قوانین لمس‌کردن نقاشی‌ها را ممنوع می‌کنند.', pronunciation: 'ذِ رولز فُربید تاچینگ ذِ پِینتینگز', vocabulary: [{ word: 'forbid', meaning: 'ممنوع کردن', essential504: true }] },
      { id: 'museum-embrace', en: 'The new gallery embraces both art and technology.', fa: 'گالری جدید هم هنر و هم فناوری را می‌پذیرد.', pronunciation: 'ذِ نیو گَلِری اِمبریسِز بوث آرت اَند تِکنالِجی', vocabulary: [{ word: 'embrace', meaning: 'پذیرفتن / دربرگرفتن', essential504: true }] },
      { id: 'museum-architect', en: 'A young architect designed this building.', fa: 'یک معمار جوان این ساختمان را طراحی کرده است.', pronunciation: 'اَ یانگ آرکیتِکت دیزایند ذیس بیلدینگ', vocabulary: [{ word: 'architect', meaning: 'معمار', essential504: true }] },
      { id: 'museum-guide', en: 'The guided tour starts at noon.', fa: 'بازدید همراه راهنما ظهر شروع می‌شود.', pronunciation: 'ذِ گایدِد تور اِستارتس اَت نون', vocabulary: [{ word: 'guided tour', meaning: 'بازدید همراه راهنما' }] },
      { id: 'museum-ticket', en: 'Keep your ticket until you leave.', fa: 'بلیطتان را تا زمان خروج نگه دارید.', pronunciation: 'کیپ یور تیکِت اَنتیل یو لیو', vocabulary: [{ word: 'ticket', meaning: 'بلیط' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Who designed this building?', fa: 'چه کسی این ساختمان را طراحی کرده؟' },
      { speaker: 'learner', text: 'A young architect designed it.', fa: 'یک معمار جوان آن را طراحی کرده است.' },
      { speaker: 'partner', text: 'Can I touch the artwork?', fa: 'می‌توانم آثار هنری را لمس کنم؟' },
      { speaker: 'learner', text: 'No. The rules forbid touching anything on exhibit.', fa: 'نه. قوانین لمس آثار نمایشگاه را ممنوع می‌کنند.' },
    ],
  },
  {
    id: 'advanced-mediating-a-disagreement', levelId: 4, order: 49,
    title: 'میانجیگری در اختلاف', subtitle: 'حفظ بی‌طرفی و شنیدن دو طرف',
    situation: 'دو همکار اختلاف دارند و شما باید بدون طرفداری به حل مسئله کمک کنید.', durationMinutes: 14,
    sentences: [
      { id: 'mediation-partial', en: 'A mediator must not be partial to either side.', fa: 'میانجی نباید نسبت به هیچ‌یک از طرفین جانبدار باشد.', pronunciation: 'اَ میدیِیتِر ماست نات بی پارشِل تو آیذِر ساید', vocabulary: [{ word: 'partial', meaning: 'جانبدار', essential504: true }] },
      { id: 'mediation-authority', en: 'I do not have the authority to punish anyone.', fa: 'من اختیار مجازات کسی را ندارم.', pronunciation: 'آی دو نات هَو ذی اَثورِتی تو پانیش اِنی‌وان', vocabulary: [{ word: 'authority', meaning: 'اختیار / مقام', essential504: true }] },
      { id: 'mediation-neutral', en: 'Let us meet in a neutral place.', fa: 'بیایید در مکانی بی‌طرفانه ملاقات کنیم.', pronunciation: 'لِت آس میت این اَ نیوترِل پِلِیس', vocabulary: [{ word: 'neutral', meaning: 'بی‌طرف', essential504: true }] },
      { id: 'mediation-consider', en: 'Please consider the other person’s concerns.', fa: 'لطفاً نگرانی‌های طرف مقابل را در نظر بگیرید.', pronunciation: 'پلیز کِنسیدِر ذی آذِر پِرسِنز کِنسِرنز', vocabulary: [{ word: 'consider', meaning: 'در نظر گرفتن', essential504: true }] },
      { id: 'mediation-turn', en: 'Each person will have time to speak.', fa: 'هر فرد زمانی برای صحبت خواهد داشت.', pronunciation: 'ایچ پِرسِن ویل هَو تایم تو اِسپیک', vocabulary: [{ word: 'each person', meaning: 'هر فرد' }] },
      { id: 'mediation-solution', en: 'Our goal is a fair solution.', fa: 'هدف ما یک راه‌حل عادلانه است.', pronunciation: 'آور گول ایز اَ فِر سِلوشِن', vocabulary: [{ word: 'fair solution', meaning: 'راه‌حل عادلانه' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Whose side are you on?', fa: 'طرف چه کسی هستید؟' },
      { speaker: 'learner', text: 'Neither. I must remain neutral and not be partial.', fa: 'هیچ‌کدام. باید بی‌طرف بمانم و جانبداری نکنم.' },
      { speaker: 'partner', text: 'What should I do?', fa: 'چه کاری باید انجام دهم؟' },
      { speaker: 'learner', text: 'Consider the other person’s concerns and look for a fair solution.', fa: 'نگرانی‌های طرف مقابل را در نظر بگیر و دنبال راه‌حل عادلانه باش.' },
    ],
  },
  {
    id: 'advanced-handling-rude-behavior', levelId: 4, order: 50,
    title: 'برخورد با رفتار بی‌ادبانه', subtitle: 'بیان مخالفت بدون تشدید تنش',
    situation: 'در یک جلسه فردی با حالت و لحن نامناسب صحبت می‌کند و شما می‌خواهید محترمانه مرز تعیین کنید.', durationMinutes: 13,
    sentences: [
      { id: 'behavior-fierce', en: 'The discussion became fierce within minutes.', fa: 'بحث در چند دقیقه بسیار شدید شد.', pronunciation: 'ذِ دیسکاشِن بِکِیم فیرس ویدین مینیتس', vocabulary: [{ word: 'fierce', meaning: 'شدید / خشن', essential504: true }] },
      { id: 'behavior-detest', en: 'I detest personal insults during a debate.', fa: 'از توهین شخصی هنگام بحث بیزارم.', pronunciation: 'آی دیتِست پِرسِنِل اینسالتس دیورینگ اَ دِبِیت', vocabulary: [{ word: 'detest', meaning: 'بیزار بودن', essential504: true }] },
      { id: 'behavior-sneer', en: 'Please do not sneer at other people’s ideas.', fa: 'لطفاً ایده‌های دیگران را با تمسخر رد نکنید.', pronunciation: 'پلیز دو نات اِسنیر اَت آذِر پیپِلز آیدیاز', vocabulary: [{ word: 'sneer', meaning: 'با تمسخر نگاه یا صحبت کردن', essential504: true }] },
      { id: 'behavior-scowl', en: 'He began to scowl when I disagreed.', fa: 'وقتی مخالفت کردم اخم کرد.', pronunciation: 'هی بِگَن تو اِسکَول وِن آی دیس‌اَگرید', vocabulary: [{ word: 'scowl', meaning: 'اخم کردن', essential504: true }] },
      { id: 'behavior-calm', en: 'Let us lower our voices and continue calmly.', fa: 'بیایید صدایمان را پایین بیاوریم و آرام ادامه دهیم.', pronunciation: 'لِت آس لوئِر آور وُیسِز اَند کِنتینیو کاملی', vocabulary: [{ word: 'lower your voice', meaning: 'پایین‌آوردن صدا' }] },
      { id: 'behavior-break', en: 'We can take a short break if needed.', fa: 'در صورت نیاز می‌توانیم کمی استراحت کنیم.', pronunciation: 'وی کَن تِیک اَ شورت بریک ایف نیدِد', vocabulary: [{ word: 'break', meaning: 'وقفه / استراحت' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why did you stop the discussion?', fa: 'چرا بحث را متوقف کردید؟' },
      { speaker: 'learner', text: 'It became fierce, and people began to sneer at each other.', fa: 'بحث شدید شد و افراد شروع به تمسخر یکدیگر کردند.' },
      { speaker: 'partner', text: 'What should we do now?', fa: 'حالا چه کار کنیم؟' },
      { speaker: 'learner', text: 'Lower our voices and avoid personal insults.', fa: 'صدایمان را پایین بیاوریم و از توهین شخصی دوری کنیم.' },
    ],
  },
  {
    id: 'advanced-supporting-someone-brave', levelId: 4, order: 51,
    title: 'حمایت از یک فرد شجاع', subtitle: 'تشویق در شرایط دشوار',
    situation: 'یکی از دوستانتان برای دفاع از دیگران کار شجاعانه‌ای انجام داده و اکنون به حمایت نیاز دارد.', durationMinutes: 13,
    sentences: [
      { id: 'support-encourage', en: 'We should encourage her to continue.', fa: 'باید او را تشویق کنیم که ادامه دهد.', pronunciation: 'وی شود اِنکِرِج هِر تو کِنتینیو', vocabulary: [{ word: 'encourage', meaning: 'تشویق کردن', essential504: true }] },
      { id: 'support-symbol', en: 'Her action became a symbol of hope.', fa: 'کار او به نمادی از امید تبدیل شد.', pronunciation: 'هِر اَکشِن بِکِیم اَ سیمبِل آو هوپ', vocabulary: [{ word: 'symbol', meaning: 'نماد', essential504: true }] },
      { id: 'support-trifle', en: 'Do not let a minor trifle distract you.', fa: 'اجازه نده یک موضوع کوچک حواست را پرت کند.', pronunciation: 'دو نات لِت اَ ماینِر تِرایفِل دیسترَکت یو', vocabulary: [{ word: 'trifle', meaning: 'چیز یا موضوع کم‌اهمیت', essential504: true }] },
      { id: 'support-valiant', en: 'It was a valiant effort to protect others.', fa: 'این تلاشی شجاعانه برای محافظت از دیگران بود.', pronunciation: 'ایت واز اَ وَلْیِنت اِفِرت تو پروتِکت آذِرز', vocabulary: [{ word: 'valiant', meaning: 'شجاعانه', essential504: true }] },
      { id: 'support-rest', en: 'You also need time to rest and recover.', fa: 'برای استراحت و بازیابی هم به زمان نیاز دارید.', pronunciation: 'یو آلسو نید تایم تو رِست اَند ریکاوِر', vocabulary: [{ word: 'recover', meaning: 'بازیابی‌شدن' }] },
      { id: 'support-help', en: 'You do not have to face this alone.', fa: 'لازم نیست به‌تنهایی با این موضوع روبه‌رو شوید.', pronunciation: 'یو دو نات هَو تو فِیس ذیس اَلون', vocabulary: [{ word: 'alone', meaning: 'تنها' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Was her effort successful?', fa: 'تلاش او موفق بود؟' },
      { speaker: 'learner', text: 'Yes. It was a valiant effort and became a symbol of hope.', fa: 'بله. تلاشی شجاعانه بود و به نماد امید تبدیل شد.' },
      { speaker: 'partner', text: 'How can we help?', fa: 'چطور می‌توانیم کمک کنیم؟' },
      { speaker: 'learner', text: 'Encourage her and do not focus on every trifle.', fa: 'او را تشویق کنیم و روی هر موضوع کوچکی تمرکز نکنیم.' },
    ],
  },
  {
    id: 'advanced-preparing-for-travel-abroad', levelId: 4, order: 52,
    title: 'آمادگی برای سفر خارجی', subtitle: 'مدیریت وسایل و هزینه‌ها',
    situation: 'برای نخستین سفر خارجی آماده می‌شوید و درباره چمدان، هزینه و تجربه دیگران صحبت می‌کنید.', durationMinutes: 13,
    sentences: [
      { id: 'travel-baggage', en: 'Your baggage must stay under the weight limit.', fa: 'بار شما باید زیر محدودیت وزن بماند.', pronunciation: 'یور بَگِج ماست اِستِی آندِر ذِ وِیت لیمیت', vocabulary: [{ word: 'baggage', meaning: 'بار و چمدان', essential504: true }] },
      { id: 'travel-abroad', en: 'This is my first time traveling abroad.', fa: 'این اولین سفر من به خارج از کشور است.', pronunciation: 'ذیس ایز مای فِرست تایم تِرَوِلینگ اَبراد', vocabulary: [{ word: 'abroad', meaning: 'در خارج از کشور', essential504: true }] },
      { id: 'travel-squander', en: 'Do not squander your money on the first day.', fa: 'در روز اول پولتان را بیهوده خرج نکنید.', pronunciation: 'دو نات اِسکواندِر یور مانی آن ذِ فِرست دِی', vocabulary: [{ word: 'squander', meaning: 'بیهوده خرج‌کردن', essential504: true }] },
      { id: 'travel-envy', en: 'I used to envy friends who traveled often.', fa: 'قبلاً به دوستانی که زیاد سفر می‌کردند حسادت می‌کردم.', pronunciation: 'آی یوست تو اِنوی فِرِندز هو تِرَوِلد آفِن', vocabulary: [{ word: 'envy', meaning: 'حسادت / رشک', essential504: true }] },
      { id: 'travel-copy', en: 'Keep a digital copy of your passport.', fa: 'یک نسخه دیجیتال از گذرنامه خود نگه دارید.', pronunciation: 'کیپ اَ دیجیتِل کاپی آو یور پَسپورت', vocabulary: [{ word: 'digital copy', meaning: 'نسخه دیجیتال' }] },
      { id: 'travel-budget', en: 'Set a daily budget before you leave.', fa: 'پیش از حرکت یک بودجه روزانه تعیین کنید.', pronunciation: 'سِت اَ دِیلی باجِت بیفور یو لیو', vocabulary: [{ word: 'daily budget', meaning: 'بودجه روزانه' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Is this your first trip abroad?', fa: 'این اولین سفر خارجی شماست؟' },
      { speaker: 'learner', text: 'Yes. I need to check my baggage and make a budget.', fa: 'بله. باید بارم را بررسی و بودجه تعیین کنم.' },
      { speaker: 'partner', text: 'Good. Do not squander your money on the first day.', fa: 'خوب است. روز اول پولت را بیهوده خرج نکن.' },
    ],
  },
  {
    id: 'advanced-responding-to-a-building-disaster', levelId: 4, order: 53,
    title: 'واکنش به حادثه ساختمانی', subtitle: 'توضیح خطر و مسئولیت قانونی',
    situation: 'بخشی از یک ساختمان فرو ریخته و درباره علت، خطرهای باقی‌مانده و بررسی قانونی صحبت می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'disaster-calamity', en: 'The collapse was a terrible calamity for the town.', fa: 'فروریختن ساختمان فاجعه‌ای وحشتناک برای شهر بود.', pronunciation: 'ذِ کِلَپس واز اَ تِرِبِل کِلَمِتی فُر ذِ تاون', vocabulary: [{ word: 'calamity', meaning: 'فاجعه', essential504: true }] },
      { id: 'disaster-collapse', en: 'Part of the roof began to collapse.', fa: 'بخشی از سقف شروع به فروریختن کرد.', pronunciation: 'پارت آو ذِ روف بِگَن تو کِلَپس', vocabulary: [{ word: 'collapse', meaning: 'فروریختن', essential504: true }] },
      { id: 'disaster-prosecute', en: 'Officials may prosecute those responsible.', fa: 'ممکن است مسئولان افراد مقصر را تحت پیگرد قرار دهند.', pronunciation: 'اُفیشِلز مِی پراسِکیوت ذوز ریسپانْسِبِل', vocabulary: [{ word: 'prosecute', meaning: 'تحت پیگرد قانونی قرار دادن', essential504: true }] },
      { id: 'disaster-threat', en: 'The damaged wall remains a threat to safety.', fa: 'دیوار آسیب‌دیده همچنان تهدیدی برای ایمنی است.', pronunciation: 'ذِ دَمِجد وال ریمِینز اَ ثرِت تو سِیفْتی', vocabulary: [{ word: 'threat', meaning: 'تهدید', essential504: true }] },
      { id: 'disaster-area', en: 'Keep everyone away from the area.', fa: 'همه را از منطقه دور نگه دارید.', pronunciation: 'کیپ اِوری‌وان اَوِی فرام ذی اِریا', vocabulary: [{ word: 'keep away', meaning: 'دور نگه‌داشتن' }] },
      { id: 'disaster-inspect', en: 'Engineers will inspect the remaining structure.', fa: 'مهندسان سازه باقی‌مانده را بررسی خواهند کرد.', pronunciation: 'اِنجینیرز ویل اینسپِکت ذِ ریمِینینگ اِسترَکچِر', vocabulary: [{ word: 'structure', meaning: 'سازه' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Is the area safe now?', fa: 'منطقه الان امن است؟' },
      { speaker: 'learner', text: 'No. The damaged wall is still a threat and may collapse.', fa: 'نه. دیوار آسیب‌دیده هنوز خطرناک است و ممکن است فرو بریزد.' },
      { speaker: 'partner', text: 'Will anyone be prosecuted?', fa: 'کسی تحت پیگرد قرار می‌گیرد؟' },
      { speaker: 'learner', text: 'Officials will investigate who was responsible for the calamity.', fa: 'مسئولان بررسی می‌کنند چه کسی مسئول فاجعه بوده است.' },
    ],
  },
  {
    id: 'advanced-discussing-animal-protection', levelId: 4, order: 54,
    title: 'گفت‌وگو درباره حفاظت حیوانات', subtitle: 'توضیح نگرانی و قوانین نگهداری',
    situation: 'درباره نگهداری حیوانات وحشی و اثر قوانین جدید بر امنیت آن‌ها گفت‌وگو می‌کنید.', durationMinutes: 13,
    sentences: [
      { id: 'animals-ban', en: 'The new law will ban the sale of wild animals.', fa: 'قانون جدید فروش حیوانات وحشی را ممنوع می‌کند.', pronunciation: 'ذِ نیو لا ویل بَن ذِ سِیل آو وایلد اَنیمِلز', vocabulary: [{ word: 'ban', meaning: 'ممنوع کردن', essential504: true }] },
      { id: 'animals-uneasy', en: 'I feel uneasy when I see animals in tiny cages.', fa: 'وقتی حیوانات را در قفس‌های کوچک می‌بینم ناراحت و نگران می‌شوم.', pronunciation: 'آی فیل اَنیزی وِن آی سی اَنیمِلز این تاینِی کِیجِز', vocabulary: [{ word: 'uneasy', meaning: 'نگران / ناراحت', essential504: true }] },
      { id: 'animals-captive', en: 'A captive animal still needs space and care.', fa: 'حیوان در اسارت همچنان به فضا و مراقبت نیاز دارد.', pronunciation: 'اَ کَپتیو اَنیمِل اِستیل نیدز اِسپِیس اَند کِر', vocabulary: [{ word: 'captive', meaning: 'در اسارت', essential504: true }] },
      { id: 'animals-devour', en: 'Large predators can devour several kilos of food.', fa: 'شکارچیان بزرگ می‌توانند چندین کیلو غذا را ببلعند.', pronunciation: 'لارج پِرِدِتِرز کَن دِوَور سِوِرِل کیلوز آو فود', vocabulary: [{ word: 'devour', meaning: 'با حرص خوردن / بلعیدن', essential504: true }] },
      { id: 'animals-habitat', en: 'Protecting natural habitats is the best solution.', fa: 'محافظت از زیستگاه طبیعی بهترین راه‌حل است.', pronunciation: 'پروتِکتینگ نَچرِل هَبیتَتس ایز ذِ بِست سِلوشِن', vocabulary: [{ word: 'habitat', meaning: 'زیستگاه' }] },
      { id: 'animals-expert', en: 'Only trained experts should handle these animals.', fa: 'فقط کارشناسان آموزش‌دیده باید با این حیوانات کار کنند.', pronunciation: 'اونلی تِرِیند اِکسپِرتس شود هَندِل ذیز اَنیمِلز', vocabulary: [{ word: 'trained expert', meaning: 'کارشناس آموزش‌دیده' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why do you support the ban?', fa: 'چرا از ممنوعیت حمایت می‌کنید؟' },
      { speaker: 'learner', text: 'I feel uneasy when a captive animal has no space.', fa: 'وقتی حیوان در اسارت فضا ندارد نگران می‌شوم.' },
      { speaker: 'partner', text: 'What is the best solution?', fa: 'بهترین راه‌حل چیست؟' },
      { speaker: 'learner', text: 'Protect natural habitats and let experts care for injured animals.', fa: 'از زیستگاه‌ها محافظت کنیم و مراقبت حیوانات آسیب‌دیده را به کارشناسان بسپاریم.' },
    ],
  },
  {
    id: 'advanced-analyzing-a-prison-documentary', levelId: 4, order: 55,
    title: 'بررسی یک مستند تاریخی', subtitle: 'توصیف شرایط و رفتار شخصیت‌ها',
    situation: 'پس از دیدن مستندی تاریخی درباره یک زندان، درباره شرایط و رفتار افراد حاضر در آن صحبت می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'documentary-crafty', en: 'A crafty prisoner found a way to send a message.', fa: 'یک زندانی زیرک راهی برای فرستادن پیام پیدا کرد.', pronunciation: 'اَ کِرَفتی پریزِنِر فَوند اَ وِی تو سِند اَ مِسِج', vocabulary: [{ word: 'crafty', meaning: 'زیرک / حیله‌گر', essential504: true }] },
      { id: 'documentary-defiant', en: 'He remained defiant despite the punishment.', fa: 'با وجود مجازات همچنان نافرمان و مقاوم ماند.', pronunciation: 'هی ریمِیند دِفایِنت دیسپایت ذِ پانیشمِنت', vocabulary: [{ word: 'defiant', meaning: 'نافرمان / مقاوم', essential504: true }] },
      { id: 'documentary-extract', en: 'The interviewer tried to extract the truth.', fa: 'مصاحبه‌کننده تلاش کرد حقیقت را بیرون بکشد.', pronunciation: 'ذی اینتِرویور تِراید تو اِکسترَکت ذِ تروث', vocabulary: [{ word: 'extract', meaning: 'بیرون کشیدن / استخراج کردن', essential504: true }] },
      { id: 'documentary-wretched', en: 'The prisoners lived in wretched conditions.', fa: 'زندانیان در شرایطی بسیار بد زندگی می‌کردند.', pronunciation: 'ذِ پریزِنِرز لیود این رِچِد کِندیشِنز', vocabulary: [{ word: 'wretched', meaning: 'بسیار بد و فلاکت‌بار', essential504: true }] },
      { id: 'documentary-source', en: 'The film used letters as historical sources.', fa: 'فیلم از نامه‌ها به‌عنوان منابع تاریخی استفاده کرد.', pronunciation: 'ذِ فیلم یوزد لِتِرز اَز هیستوریکِل سورسِز', vocabulary: [{ word: 'historical source', meaning: 'منبع تاریخی' }] },
      { id: 'documentary-fact', en: 'Some scenes were recreated for the documentary.', fa: 'بعضی صحنه‌ها برای مستند بازسازی شده بودند.', pronunciation: 'سام سینز وِر ریکری‌اِیتِد فُر ذِ داکیومِنتِری', vocabulary: [{ word: 'recreate', meaning: 'بازسازی کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What were the prison conditions like?', fa: 'شرایط زندان چگونه بود؟' },
      { speaker: 'learner', text: 'The prisoners lived in wretched conditions.', fa: 'زندانیان در شرایط بسیار بدی زندگی می‌کردند.' },
      { speaker: 'partner', text: 'How did the interviewer learn the truth?', fa: 'مصاحبه‌کننده چگونه حقیقت را فهمید؟' },
      { speaker: 'learner', text: 'He tried to extract facts from letters and interviews.', fa: 'تلاش کرد واقعیت‌ها را از نامه‌ها و مصاحبه‌ها بیرون بکشد.' },
    ],
  },
];
