import type { SentenceLesson } from './courseContent';

/** Fifth original content pack: 32 more 504 words in sentence-first situations. */
export const ADVANCED_SENTENCE_LESSONS_4: SentenceLesson[] = [
  {
    id: 'advanced-managing-a-farm-project', levelId: 4, order: 40,
    title: 'مدیریت یک پروژه کشاورزی', subtitle: 'برنامه‌ریزی تولید و رشد پایدار',
    situation: 'با اعضای یک تعاونی درباره برداشت محصول، هدف تولید و راه‌های رشد کسب‌وکار صحبت می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'farm-harvest', en: 'The wheat harvest begins next week.', fa: 'برداشت گندم هفته آینده آغاز می‌شود.', pronunciation: 'ذِ ویت هاروِست بِگینز نِکست ویک', vocabulary: [{ word: 'harvest', meaning: 'برداشت محصول', essential504: true }] },
      { id: 'farm-quota', en: 'Each farm has a weekly delivery quota.', fa: 'هر مزرعه سهمیه تحویل هفتگی دارد.', pronunciation: 'ایچ فارم هَز اَ ویکلی دِلیوِری کوتا', vocabulary: [{ word: 'quota', meaning: 'سهمیه / مقدار تعیین‌شده', essential504: true }] },
      { id: 'farm-vigor', en: 'The young plants are growing with vigor.', fa: 'گیاهان جوان با قدرت رشد می‌کنند.', pronunciation: 'ذِ یانگ پِلَنتس آر گروئینگ ویذ ویگِر', vocabulary: [{ word: 'vigor', meaning: 'قدرت و انرژی', essential504: true }] },
      { id: 'farm-prosper', en: 'Small farms can prosper through cooperation.', fa: 'مزرعه‌های کوچک می‌توانند با همکاری پیشرفت کنند.', pronunciation: 'اِسمال فارمز کَن پراسپِر ثرو کوآپِرِیشِن', vocabulary: [{ word: 'prosper', meaning: 'رونق گرفتن / پیشرفت کردن', essential504: true }] },
      { id: 'farm-weather', en: 'We should check the weather every morning.', fa: 'باید هر صبح وضعیت هوا را بررسی کنیم.', pronunciation: 'وی شود چِک ذِ وِذِر اِوری مورنینگ', vocabulary: [{ word: 'weather', meaning: 'وضعیت هوا' }] },
      { id: 'farm-share', en: 'Let us share equipment to reduce costs.', fa: 'برای کاهش هزینه‌ها تجهیزات را مشترک استفاده کنیم.', pronunciation: 'لِت آس شِر اِکویپمِنت تو ریدیوس کاستس', vocabulary: [{ word: 'cooperation', meaning: 'همکاری' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'When does the harvest begin?', fa: 'برداشت چه زمانی آغاز می‌شود؟' },
      { speaker: 'learner', text: 'It begins next week, and each farm has a delivery quota.', fa: 'هفته آینده آغاز می‌شود و هر مزرعه سهمیه تحویل دارد.' },
      { speaker: 'partner', text: 'Can small farms prosper?', fa: 'مزرعه‌های کوچک می‌توانند رونق بگیرند؟' },
      { speaker: 'learner', text: 'Yes, especially through cooperation.', fa: 'بله، به‌ویژه از طریق همکاری.' },
    ],
  },
  {
    id: 'advanced-protecting-delicate-equipment', levelId: 4, order: 41,
    title: 'محافظت از تجهیزات حساس', subtitle: 'بسته‌بندی و بررسی آسیب',
    situation: 'باید یک وسیله حساس را برای ارسال آماده کنید و مطمئن شوید رطوبت یا فشار به آن آسیب نمی‌زند.', durationMinutes: 13,
    sentences: [
      { id: 'equipment-absorb', en: 'This material can absorb extra moisture.', fa: 'این ماده می‌تواند رطوبت اضافی را جذب کند.', pronunciation: 'ذیس مَتیریِل کَن اَبزورب اِکسترا مویسچِر', vocabulary: [{ word: 'absorb', meaning: 'جذب کردن', essential504: true }] },
      { id: 'equipment-fragile', en: 'The equipment is extremely fragile.', fa: 'این تجهیزات بسیار شکننده هستند.', pronunciation: 'ذی اِکویپمِنت ایز اِکستریمْلی فِرَجِل', vocabulary: [{ word: 'fragile', meaning: 'شکننده / آسیب‌پذیر', essential504: true }] },
      { id: 'equipment-emerge', en: 'A small crack may emerge under pressure.', fa: 'ممکن است زیر فشار یک ترک کوچک ظاهر شود.', pronunciation: 'اَ اِسمال کِرَک مِی اِمِرج آندِر پِرِشِر', vocabulary: [{ word: 'emerge', meaning: 'ظاهر شدن', essential504: true }] },
      { id: 'equipment-linger', en: 'Moisture can linger inside a closed box.', fa: 'رطوبت می‌تواند داخل جعبه بسته باقی بماند.', pronunciation: 'مویسچِر کَن لینگِر اینساید اَ کلوزد باکس', vocabulary: [{ word: 'linger', meaning: 'باقی ماندن', essential504: true }] },
      { id: 'equipment-label', en: 'Mark the box as fragile on every side.', fa: 'روی همه طرف‌های جعبه علامت شکستنی بزنید.', pronunciation: 'مارک ذِ باکس اَز فِرَجِل آن اِوری ساید', vocabulary: [{ word: 'mark', meaning: 'علامت‌گذاری کردن' }] },
      { id: 'equipment-test', en: 'Inspect the device when it arrives.', fa: 'وقتی دستگاه رسید آن را بررسی کنید.', pronunciation: 'اینسپِکت ذِ دِوایس وِن ایت اَرایوز', vocabulary: [{ word: 'inspect', meaning: 'بازرسی کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why do we need this material?', fa: 'چرا به این ماده نیاز داریم؟' },
      { speaker: 'learner', text: 'It absorbs moisture that could linger in the box.', fa: 'رطوبتی را جذب می‌کند که ممکن است در جعبه بماند.' },
      { speaker: 'partner', text: 'Is the equipment fragile?', fa: 'تجهیزات شکننده‌اند؟' },
      { speaker: 'learner', text: 'Yes. A crack may emerge under pressure.', fa: 'بله. ممکن است زیر فشار ترک ظاهر شود.' },
    ],
  },
  {
    id: 'advanced-changing-a-hiking-route', levelId: 4, order: 42,
    title: 'تغییر مسیر پیاده‌روی', subtitle: 'واکنش آرام به شرایط سخت',
    situation: 'در مسیر کوهستانی با راهی دشوار روبه‌رو شده‌اید و باید بدون ترس، مسیر امن‌تری انتخاب کنید.', durationMinutes: 13,
    sentences: [
      { id: 'route-jagged', en: 'Jagged rocks make this path dangerous.', fa: 'سنگ‌های تیز و ناهموار این مسیر را خطرناک کرده‌اند.', pronunciation: 'جَگِد راکس مِیک ذیس پَث دِینجِرِس', vocabulary: [{ word: 'jagged', meaning: 'تیز و ناهموار', essential504: true }] },
      { id: 'route-weary', en: 'The hikers are weary after the long climb.', fa: 'کوهنوردان پس از صعود طولانی خسته‌اند.', pronunciation: 'ذِ هایکِرز آر ویری اَفتِر ذِ لانگ کِلایم', vocabulary: [{ word: 'weary', meaning: 'بسیار خسته', essential504: true }] },
      { id: 'route-detour', en: 'We should take a short detour around the cliff.', fa: 'باید از یک مسیر فرعی کوتاه دور صخره برویم.', pronunciation: 'وی شود تِیک اَ شورت دیتور اَرَوند ذِ کِلیف', vocabulary: [{ word: 'detour', meaning: 'مسیر انحرافی', essential504: true }] },
      { id: 'route-panic', en: 'Do not panic if you lose sight of the trail.', fa: 'اگر مسیر از دیدتان خارج شد وحشت نکنید.', pronunciation: 'دو نات پَنیک ایف یو لوز سایت آو ذِ تِرِیل', vocabulary: [{ word: 'panic', meaning: 'وحشت کردن', essential504: true }] },
      { id: 'route-rest', en: 'Let us rest before we continue.', fa: 'پیش از ادامه کمی استراحت کنیم.', pronunciation: 'لِت آس رِست بیفور وی کِنتینیو', vocabulary: [{ word: 'rest', meaning: 'استراحت کردن' }] },
      { id: 'route-together', en: 'Stay together and follow the marked signs.', fa: 'کنار هم بمانید و علامت‌ها را دنبال کنید.', pronunciation: 'اِستِی توگِذِر اَند فالو ذِ مارکت ساینز', vocabulary: [{ word: 'trail', meaning: 'مسیر پیاده‌روی' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why are we stopping?', fa: 'چرا توقف می‌کنیم؟' },
      { speaker: 'learner', text: 'The hikers are weary, and jagged rocks block the path.', fa: 'کوهنوردان خسته‌اند و سنگ‌های ناهموار مسیر را بسته‌اند.' },
      { speaker: 'partner', text: 'Should we panic?', fa: 'باید وحشت کنیم؟' },
      { speaker: 'learner', text: 'No. We can take a safe detour.', fa: 'نه. می‌توانیم از مسیر فرعی امن برویم.' },
    ],
  },
  {
    id: 'advanced-responding-to-a-road-accident', levelId: 4, order: 43,
    title: 'واکنش به تصادف جاده‌ای', subtitle: 'پیش‌بینی خطر و کمک آرام',
    situation: 'شاهد یک تصادف کوچک بوده‌اید و باید وضعیت را ایمن نگه دارید و اطلاعات را تأیید کنید.', durationMinutes: 14,
    sentences: [
      { id: 'accident-collide', en: 'Two cars collided near the intersection.', fa: 'دو خودرو نزدیک تقاطع با هم برخورد کردند.', pronunciation: 'تو کارز کِلایدِد نیر ذی اینتِرسِکشِن', vocabulary: [{ word: 'collide', meaning: 'برخورد کردن', essential504: true }] },
      { id: 'accident-anticipate', en: 'Drivers should anticipate sudden stops.', fa: 'رانندگان باید توقف‌های ناگهانی را پیش‌بینی کنند.', pronunciation: 'دِرایوِرز شود اَنتیسیپِیت سادِن اِستاپس', vocabulary: [{ word: 'anticipate', meaning: 'پیش‌بینی کردن', essential504: true }] },
      { id: 'accident-relieve', en: 'The news that no one was hurt relieved us.', fa: 'خبر آسیب‌ندیدن افراد خیالمان را راحت کرد.', pronunciation: 'ذِ نیوز ذَت نو وان واز هِرت ریلیود آس', vocabulary: [{ word: 'relieve', meaning: 'آسوده‌کردن / کاهش نگرانی', essential504: true }] },
      { id: 'accident-confirm', en: 'Please confirm the exact location.', fa: 'لطفاً مکان دقیق را تأیید کنید.', pronunciation: 'پلیز کِنفِرم ذی اِگزَکت لوکِیشِن', vocabulary: [{ word: 'confirm', meaning: 'تأیید کردن', essential504: true }] },
      { id: 'accident-distance', en: 'Keep a safe distance from the vehicles.', fa: 'فاصله امنی از خودروها حفظ کنید.', pronunciation: 'کیپ اَ سِیف دیستِنس فرام ذِ ویهِکِلز', vocabulary: [{ word: 'distance', meaning: 'فاصله' }] },
      { id: 'accident-call', en: 'I have already called emergency services.', fa: 'قبلاً با خدمات اضطراری تماس گرفته‌ام.', pronunciation: 'آی هَو آلرِدی کُلد اِمِرجِنسی سِرویسِز', vocabulary: [{ word: 'emergency services', meaning: 'خدمات اضطراری' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What happened?', fa: 'چه اتفاقی افتاد؟' },
      { speaker: 'learner', text: 'Two cars collided near the intersection.', fa: 'دو خودرو نزدیک تقاطع برخورد کردند.' },
      { speaker: 'partner', text: 'Was anyone hurt?', fa: 'کسی آسیب دید؟' },
      { speaker: 'learner', text: 'No, and that news relieved us. Please confirm the location for emergency services.', fa: 'نه و این خبر خیالمان را راحت کرد. لطفاً مکان را برای خدمات اضطراری تأیید کنید.' },
    ],
  },
  {
    id: 'advanced-choosing-between-two-options', levelId: 4, order: 44,
    title: 'انتخاب میان دو گزینه', subtitle: 'سنجیدن ارزش و حل سردرگمی',
    situation: 'برای ادامه تحصیل با دو انتخاب دشوار روبه‌رو هستید و مزیت‌های هر کدام را منطقی بررسی می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'choice-dilemma', en: 'I face a dilemma between cost and quality.', fa: 'میان هزینه و کیفیت با یک دوراهی روبه‌رو هستم.', pronunciation: 'آی فِیس اَ دِلِما بِتوین کاست اَند کوالِتی', vocabulary: [{ word: 'dilemma', meaning: 'دوراهی دشوار', essential504: true }] },
      { id: 'choice-merit', en: 'Each option has real merit.', fa: 'هر گزینه ارزش و مزیت واقعی دارد.', pronunciation: 'ایچ آپشِن هَز ریل مِرِت', vocabulary: [{ word: 'merit', meaning: 'ارزش / شایستگی', essential504: true }] },
      { id: 'choice-logical', en: 'A written comparison will lead to a logical choice.', fa: 'مقایسه مکتوب به انتخابی منطقی منجر می‌شود.', pronunciation: 'اَ ریتِن کِمپَریسِن ویل لید تو اَ لاجیکِل چویس', vocabulary: [{ word: 'logical', meaning: 'منطقی', essential504: true }] },
      { id: 'choice-baffle', en: 'Too many details can baffle us.', fa: 'جزئیات بیش از حد می‌توانند ما را سردرگم کنند.', pronunciation: 'تو مِنی دیتِیلز کَن بَفِل آس', vocabulary: [{ word: 'baffle', meaning: 'سردرگم کردن', essential504: true }] },
      { id: 'choice-priority', en: 'Decide which goal is your priority.', fa: 'مشخص کنید کدام هدف اولویت شماست.', pronunciation: 'دیساید ویچ گول ایز یور پرایورِتی', vocabulary: [{ word: 'priority', meaning: 'اولویت' }] },
      { id: 'choice-time', en: 'Take one day before making the final choice.', fa: 'پیش از انتخاب نهایی یک روز زمان بگذارید.', pronunciation: 'تِیک وان دِی بیفور مِیکینگ ذِ فاینِل چویس', vocabulary: [{ word: 'final choice', meaning: 'انتخاب نهایی' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'What is your dilemma?', fa: 'دوراهی شما چیست؟' },
      { speaker: 'learner', text: 'One option costs less, but each option has merit.', fa: 'یک گزینه ارزان‌تر است، اما هر کدام مزیتی دارند.' },
      { speaker: 'partner', text: 'Do not let too many details baffle you. Make a logical comparison.', fa: 'اجازه نده جزئیات زیاد سردرگمت کند. مقایسه‌ای منطقی انجام بده.' },
    ],
  },
  {
    id: 'advanced-discussing-fair-treatment', levelId: 4, order: 45,
    title: 'گفت‌وگو درباره رفتار عادلانه', subtitle: 'پذیرش مشکل و دفاع از حقوق',
    situation: 'در محل کار درباره تصمیمی صحبت می‌کنید که ممکن است بعضی افراد را از فرصت برابر محروم کند.', durationMinutes: 14,
    sentences: [
      { id: 'fairness-acknowledge', en: 'We must acknowledge that a problem exists.', fa: 'باید بپذیریم که مشکلی وجود دارد.', pronunciation: 'وی ماست اَکنالِج ذَت اَ پرابلِم اِگزیستس', vocabulary: [{ word: 'acknowledge', meaning: 'پذیرفتن / اذعان کردن', essential504: true }] },
      { id: 'fairness-justice', en: 'Everyone deserves justice and equal treatment.', fa: 'همه سزاوار عدالت و رفتار برابر هستند.', pronunciation: 'اِوری‌وان دیزِروز جاستِس اَند ایکوئِل تریت‌مِنت', vocabulary: [{ word: 'justice', meaning: 'عدالت', essential504: true }] },
      { id: 'fairness-reject', en: 'We should reject unfair rules.', fa: 'باید قوانین ناعادلانه را رد کنیم.', pronunciation: 'وی شود ریجِکت آنفِر رولز', vocabulary: [{ word: 'reject', meaning: 'رد کردن', essential504: true }] },
      { id: 'fairness-deprive', en: 'This policy could deprive people of opportunities.', fa: 'این سیاست ممکن است مردم را از فرصت‌ها محروم کند.', pronunciation: 'ذیس پالِسی کود دیپرایو پیپِل آو آپِرتیونِتیز', vocabulary: [{ word: 'deprive', meaning: 'محروم کردن', essential504: true }] },
      { id: 'fairness-review', en: 'An independent group should review the decision.', fa: 'یک گروه مستقل باید تصمیم را بررسی کند.', pronunciation: 'اَن ایندیپِندِنت گروپ شود ریویو ذِ دِسیژِن', vocabulary: [{ word: 'independent', meaning: 'مستقل' }] },
      { id: 'fairness-speak', en: 'People need a safe way to speak up.', fa: 'مردم به راهی امن برای بیان اعتراض نیاز دارند.', pronunciation: 'پیپِل نید اَ سِیف وِی تو اِسپیک آپ', vocabulary: [{ word: 'speak up', meaning: 'صریح صحبت‌کردن' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Why should we change this policy?', fa: 'چرا باید این سیاست را تغییر دهیم؟' },
      { speaker: 'learner', text: 'It could deprive people of equal opportunities.', fa: 'ممکن است مردم را از فرصت برابر محروم کند.' },
      { speaker: 'partner', text: 'What should we do first?', fa: 'ابتدا چه کار کنیم؟' },
      { speaker: 'learner', text: 'Acknowledge the problem and reject unfair rules.', fa: 'مشکل را بپذیریم و قوانین ناعادلانه را رد کنیم.' },
    ],
  },
  {
    id: 'advanced-planning-family-protection', levelId: 4, order: 46,
    title: 'برنامه‌ریزی برای حمایت خانواده', subtitle: 'انتخاب شغل و ثبت فرد دریافت‌کننده',
    situation: 'با یک مشاور درباره وضعیت کاری و برنامه‌ای برای حمایت مالی خانواده در شرایط نامطمئن صحبت می‌کنید.', durationMinutes: 14,
    sentences: [
      { id: 'family-beneficiary', en: 'You must name a beneficiary on this form.', fa: 'باید در این فرم نام فرد دریافت‌کننده مزایا را بنویسید.', pronunciation: 'یو ماست نِیم اَ بِنِفیشیِری آن ذیس فورم', vocabulary: [{ word: 'beneficiary', meaning: 'ذی‌نفع / دریافت‌کننده مزایا', essential504: true }] },
      { id: 'family-spouse', en: 'You may choose your spouse as the beneficiary.', fa: 'می‌توانید همسر خود را به‌عنوان ذی‌نفع انتخاب کنید.', pronunciation: 'یو مِی چوز یور اِسپَوس اَز ذِ بِنِفیشیِری', vocabulary: [{ word: 'spouse', meaning: 'همسر', essential504: true }] },
      { id: 'family-vocation', en: 'Teaching has always been my chosen vocation.', fa: 'معلمی همیشه حرفه انتخابی من بوده است.', pronunciation: 'تیچینگ هَز آلوِیز بین مای چوزِن وُکِیشِن', vocabulary: [{ word: 'vocation', meaning: 'حرفه / شغل مورد علاقه', essential504: true }] },
      { id: 'family-unstable', en: 'My income is unstable at the moment.', fa: 'درآمد من در حال حاضر ثابت نیست.', pronunciation: 'مای اینکام ایز آنستِیبِل اَت ذِ مومِنت', vocabulary: [{ word: 'unstable', meaning: 'بی‌ثبات', essential504: true }] },
      { id: 'family-save', en: 'I want to build an emergency fund.', fa: 'می‌خواهم یک پس‌انداز اضطراری ایجاد کنم.', pronunciation: 'آی وانت تو بیلد اَن اِمِرجِنسی فاند', vocabulary: [{ word: 'emergency fund', meaning: 'پس‌انداز اضطراری' }] },
      { id: 'family-update', en: 'Update the form after any major change.', fa: 'پس از هر تغییر مهم فرم را به‌روزرسانی کنید.', pronunciation: 'آپدِیت ذِ فورم اَفتِر اِنی مِیجِر چِینج', vocabulary: [{ word: 'major change', meaning: 'تغییر مهم' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Who will be your beneficiary?', fa: 'چه کسی ذی‌نفع شما خواهد بود؟' },
      { speaker: 'learner', text: 'I will choose my spouse.', fa: 'همسرم را انتخاب می‌کنم.' },
      { speaker: 'partner', text: 'Is your income stable?', fa: 'درآمدتان ثابت است؟' },
      { speaker: 'learner', text: 'Not yet. My vocation is teaching, but my income is unstable now.', fa: 'هنوز نه. حرفه من معلمی است، اما فعلاً درآمدم ثابت نیست.' },
    ],
  },
  {
    id: 'advanced-preparing-for-a-safe-visit', levelId: 4, order: 47,
    title: 'آمادگی برای بازدید ایمن', subtitle: 'اقدامات قبلی و احتیاط لازم',
    situation: 'پیش از ورود به یک کارگاه صنعتی، راهنما قوانین و اقدامات ایمنی لازم را توضیح می‌دهد.', durationMinutes: 13,
    sentences: [
      { id: 'visit-precaution', en: 'Wearing safety glasses is a basic precaution.', fa: 'استفاده از عینک ایمنی یک اقدام احتیاطی پایه است.', pronunciation: 'وِرینگ سِیفْتی گِلَسِز ایز اَ بِیسیک پریکاشِن', vocabulary: [{ word: 'precaution', meaning: 'اقدام احتیاطی', essential504: true }] },
      { id: 'visit-prior', en: 'Prior approval is required for every visitor.', fa: 'تأیید قبلی برای هر بازدیدکننده لازم است.', pronunciation: 'پرایِر اَپرووِل ایز ریکوایِرد فُر اِوری ویزیتِر', vocabulary: [{ word: 'prior', meaning: 'قبلی / پیشین', essential504: true }] },
      { id: 'visit-rarely', en: 'Accidents rarely happen when rules are followed.', fa: 'وقتی قوانین رعایت شوند، حوادث به‌ندرت رخ می‌دهند.', pronunciation: 'اَکسیدِنتس رِرلی هَپِن وِن رولز آر فالود', vocabulary: [{ word: 'rarely', meaning: 'به‌ندرت', essential504: true }] },
      { id: 'visit-proceed', en: 'Do not proceed until the guide arrives.', fa: 'تا رسیدن راهنما ادامه ندهید.', pronunciation: 'دو نات پروسید اَنتیل ذِ گاید اَرایوز', vocabulary: [{ word: 'proceed', meaning: 'ادامه دادن / پیش رفتن', essential504: true }] },
      { id: 'visit-helmet', en: 'Keep your helmet on inside the workshop.', fa: 'داخل کارگاه کلاه ایمنی را روی سرتان نگه دارید.', pronunciation: 'کیپ یور هِلمِت آن اینساید ذِ وِرک‌شاپ', vocabulary: [{ word: 'helmet', meaning: 'کلاه ایمنی' }] },
      { id: 'visit-line', en: 'Stay behind the yellow safety line.', fa: 'پشت خط زرد ایمنی بمانید.', pronunciation: 'اِستِی بیهایند ذِ یِلو سِیفْتی لاین', vocabulary: [{ word: 'safety line', meaning: 'خط ایمنی' }] },
    ],
    dialogue: [
      { speaker: 'partner', text: 'Can we proceed now?', fa: 'می‌توانیم الان ادامه دهیم؟' },
      { speaker: 'learner', text: 'No. Prior approval is required, and the guide has not arrived.', fa: 'نه. تأیید قبلی لازم است و راهنما نرسیده است.' },
      { speaker: 'partner', text: 'Do accidents happen often?', fa: 'حوادث زیاد رخ می‌دهند؟' },
      { speaker: 'learner', text: 'Rarely, when everyone takes basic precautions.', fa: 'وقتی همه احتیاط‌های پایه را رعایت کنند، به‌ندرت.' },
    ],
  },
];
